// constants/masterData.ts

export type ItemType = {
  id: string;
  title: string;
  icon: string;
  tags: string[]; // Algoritma için anahtar kelimeler
  description: string;
};

export const MASTER_DATA: ItemType[] = [
  // =================================================================
  // 🌯 SOKAK LEZZETLERİ & FAST FOOD (Hızlı, Ucuz, Doyurucu) - DEVAM
  // =================================================================
  { id: 'f81', title: 'Kaşarlı Kumpir', icon: '🥔', tags: ['food', 'hungry', 'mid-budget', 'student'], description: 'Bol kaşar eritilmiş, tereyağlı patates.' },
  { id: 'f82', title: 'Sucuklu Kaşarlı Tost', icon: '🥪', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Tost makinesinde çıtır çıtır.' },
  { id: 'f83', title: 'Köylü Tost', icon: '🥪', tags: ['food', 'hungry', 'low-budget', 'fast'], description: 'Sucuk, salam, sosis, kaşar - hepsi bir arada.' },
  { id: 'f84', title: 'Kavurmalı Ekmek', icon: '🥙', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sabah kahvaltısının sultanı.' },
  { id: 'f85', title: 'Pastırmalı Yumurta', icon: '🍳', tags: ['food', 'hungry', 'mid-budget', 'morning'], description: 'Çemen kokusu her yeri sarsın.' },
  { id: 'f86', title: 'Sahanda Yumurta', icon: '🍳', tags: ['food', 'snack', 'low-budget', 'morning'], description: 'Beyazı pişkin, sarısı bamya gibi.' },
  { id: 'f87', title: 'Menemen (Sucuklu)', icon: '🍳', tags: ['food', 'hungry', 'low-budget', 'morning'], description: 'Sucuk yağını salmış, domatesle buluşmuş.' },
  { id: 'f88', title: 'Çıtır Kızarmış Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Dışı çıtır, içi yumuşacık.' },
  { id: 'f89', title: 'Dürüm Döner (Kırmızı Et)', icon: '🌯', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Yağlı olsun, bol baharatlı olsun.' },
  { id: 'f90', title: 'Kuzu Tandır Dürüm', icon: '🌯', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Ağızda dağılan etin dürüm hali.' },
  { id: 'f91', title: 'Köfte Ekmek (İzmir)', icon: '🍔', tags: ['food', 'hungry', 'mid-budget', 'street'], description: 'İzmir usulü, bol soğanlı.' },
  { id: 'f92', title: 'Kumru (Özel Soslu)', icon: '🥪', tags: ['food', 'hungry', 'mid-budget', 'street'], description: 'Çeşme nin o meşhur lezzeti.' },
  { id: 'f93', title: 'Tavuk Şiş', icon: '🍢', tags: ['food', 'hungry', 'mid-budget', 'street'], description: 'Marinde bekletilmiş, ızgarada pişmiş.' },
  { id: 'f94', title: 'Kıyma Şiş', icon: '🍢', tags: ['food', 'hungry', 'mid-budget', 'street'], description: 'Baharatlar içinde kaybolmuş.' },
  { id: 'f95', title: 'Ciğer Şiş', icon: '🍢', tags: ['food', 'hungry', 'mid-budget', 'street'], description: 'Sumaklı soğanla servis edilir.' },
  { id: 'f96', title: 'Kuzu Şiş', icon: '🍢', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Tadına doyum olmaz.' },
  { id: 'f97', title: 'Tavuk Kanat', icon: '🍗', tags: ['food', 'snack', 'mid-budget', 'street'], description: 'Acılı, ballı, soslu çeşit çeşit.' },
  { id: 'f98', title: 'Köfte (İnegöl)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Ince kıyılmış, özel baharatlı.' },
  { id: 'f99', title: 'Köfte (Sulu)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Domatesli sosunda pişmiş.' },
  { id: 'f100', title: 'Köfte (Tire)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'İzmir in o meşhur köftesi.' },
  { id: 'f101', title: 'Köfte (Dalyan)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Muğla nın efsane lezzeti.' },
  { id: 'f102', title: 'Kuzu Pirzola', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Izgarada nar gibi kızarmış.' },
  { id: 'f103', title: 'Kuzu İncik', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Fırında saatlerce pişmiş.' },
  { id: 'f104', title: 'Kuzu Kol', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Kemik suyuna ekmek banılır.' },
  { id: 'f105', title: 'Kuzu Kaburga', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Yağlı ama bir o kadar lezzetli.' },
  { id: 'f106', title: 'Kuzu Göğüs', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Ağızda dağılan et.' },
  { id: 'f107', title: 'Dana Bonfile', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Medium pişmiş, terbiyeli.' },
  { id: 'f108', title: 'Dana Antrikot', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Kalın kesilmiş, ızgarada pişmiş.' },
  { id: 'f109', title: 'Dana Kontrfile', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Yumuşacık, lezzetli.' },
  { id: 'f110', title: 'Dana T-Bone', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Hem bonfile hem de kontrfile.' },
  { id: 'f111', title: 'Dana Rosto', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Fırında yavaş yavaş pişmiş.' },
  { id: 'f112', title: 'Dana Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sebzelerle birlikte pişmiş.' },
  { id: 'f113', title: 'Tavuk Sote', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Domates, biber, soğanla.' },
  { id: 'f114', title: 'Hindi Sote', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Tavuk soteden farklı bir lezzet.' },
  { id: 'f115', title: 'Kuzu Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kuzu etinin sotesi de olur.' },
  { id: 'f116', title: 'Kıyma Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kahvaltıların vazgeçilmezi.' },
  { id: 'f117', title: 'Sucuk Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sucuk yağını salmış, yumurtayla buluşmuş.' },
  { id: 'f118', title: 'Pastırma Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Pastırmanın farklı bir hali.' },
  { id: 'f119', title: 'Kavurma Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kavurma ile yapılan sote.' },
  { id: 'f120', title: 'Ciğer Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Soğanla birlikte pişmiş.' },
  { id: 'f121', title: 'Böbrek Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Seveni çok, sevmeyeni az.' },
  { id: 'f122', title: 'Yürek Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Demir açısından zengin.' },
  { id: 'f123', title: 'İşkembe Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'İşkembenin sotesi de olur mu?' },
  { id: 'f124', title: 'Kelle Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kellenin sotesi de yapılır.' },
  { id: 'f125', title: 'Paça Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Paçanın sotesi de olur.' },
  { id: 'f126', title: 'Kuzu İşkembesi', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kuzu işkembesi çorbası.' },
  { id: 'f127', title: 'Dana İşkembesi', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Dana işkembesi çorbası.' },
  { id: 'f128', title: 'Koyun İşkembesi', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Koyun işkembesi çorbası.' },
  { id: 'f129', title: 'İşkembe Çorbası', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sarımsaklı, limonlu.' },
  { id: 'f130', title: 'Paça Çorbası', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kelle paça çorbası.' },
  { id: 'f131', title: 'Kelle Paça Çorbası', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kelle ve paça birlikte.' },
  { id: 'f132', title: 'İşkembe (Çorba Değil)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış işkembe.' },
  { id: 'f133', title: 'Paça (Çorba Değil)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış paça.' },
  { id: 'f134', title: 'Kelle (Çorba Değil)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış kelle.' },
  { id: 'f135', title: 'Beyin (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış beyin.' },
  { id: 'f136', title: 'Beyin (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış beyin.' },
  { id: 'f137', title: 'Beyin Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş beyin.' },
  { id: 'f138', title: 'Dil (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış dil.' },
  { id: 'f139', title: 'Dil (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış dil.' },
  { id: 'f140', title: 'Dil Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş dil.' },
  { id: 'f141', title: 'Yürek (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış yürek.' },
  { id: 'f142', title: 'Yürek (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış yürek.' },
  { id: 'f143', title: 'Yürek Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş yürek.' },
  { id: 'f144', title: 'Böbrek (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış böbrek.' },
  { id: 'f145', title: 'Böbrek (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış böbrek.' },
  { id: 'f146', title: 'Böbrek Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş böbrek.' },
  { id: 'f147', title: 'Ciğer (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış ciğer.' },
  { id: 'f148', title: 'Ciğer (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış ciğer.' },
  { id: 'f149', title: 'Ciğer Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş ciğer.' },
  { id: 'f150', title: 'Dalak (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış dalak.' },
  { id: 'f151', title: 'Dalak (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış dalak.' },
  { id: 'f152', title: 'Dalak Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş dalak.' },
  { id: 'f153', title: 'İşkembe (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış işkembe.' },
  { id: 'f154', title: 'İşkembe (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış işkembe.' },
  { id: 'f155', title: 'İşkembe Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş işkembe.' },
  { id: 'f156', title: 'Paça (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış paça.' },
  { id: 'f157', title: 'Paça (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış paça.' },
  { id: 'f158', title: 'Paça Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş paça.' },
  { id: 'f159', title: 'Kelle (Haşlanmış)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış kelle.' },
  { id: 'f160', title: 'Kelle (Kızartma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış kelle.' },
  { id: 'f161', title: 'Kelle Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş kelle.' },
  { id: 'f162', title: 'Testi Kebabı', icon: '🏺', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Testide pişmiş, özel soslu.' },
  { id: 'f163', title: 'Fırın Kebabı', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Fırında pişmiş, tereyağlı.' },
  { id: 'f164', title: 'Tandır Kebabı', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Tandırda pişmiş, ağızda dağılan.' },
  { id: 'f165', title: 'Çökertme Kebabı', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Patates ve yoğurtla servis edilir.' },
  { id: 'f166', title: 'Beyti Kebabı', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Lavaşa sarılı, yoğurtlu.' },
  { id: 'f167', title: 'Patlıcan Kebabı', icon: '🍆', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Patlıcanla birlikte pişmiş.' },
  { id: 'f168', title: 'Domates Kebabı', icon: '🍅', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Domatesle birlikte pişmiş.' },
  { id: 'f169', title: 'Biber Kebabı', icon: '🫑', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Biberle birlikte pişmiş.' },
  { id: 'f170', title: 'Soğan Kebabı', icon: '🧅', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Soğanla birlikte pişmiş.' },
  { id: 'f171', title: 'Mantar Kebabı', icon: '🍄', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Mantarla birlikte pişmiş.' },
  { id: 'f172', title: 'Sebzeli Kebap', icon: '🥦', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Çeşitli sebzelerle pişmiş.' },
  { id: 'f173', title: 'Kıymalı Kebap', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kıymayla yapılan kebap.' },
  { id: 'f174', title: 'Kuşbaşılı Kebap', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kuşbaşı etle yapılan kebap.' },
  { id: 'f175', title: 'Bonfile Kebap', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Bonfile etle yapılan kebap.' },
  { id: 'f176', title: 'Antrikot Kebap', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Antrikot etle yapılan kebap.' },
  { id: 'f177', title: 'Kontrfile Kebap', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Kontrfile etle yapılan kebap.' },
  { id: 'f178', title: 'T-Bone Kebap', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'T-Bone etle yapılan kebap.' },
  { id: 'f179', title: 'Rosto Kebap', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Rosto etle yapılan kebap.' },
  { id: 'f180', title: 'Sote Kebap', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sote edilmiş kebap.' },
  { id: 'f181', title: 'Haşlama Kebap', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Haşlanmış kebap.' },
  { id: 'f182', title: 'Kızartma Kebap', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kızartılmış kebap.' },
  { id: 'f183', title: 'Fırın Kebap', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Fırında pişirilmiş kebap.' },
  { id: 'f184', title: 'Izgara Kebap', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Izgarada pişirilmiş kebap.' },
  { id: 'f185', title: 'Tava Kebap', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Tavada pişirilmiş kebap.' },
  { id: 'f186', title: 'Tencere Kebap', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Tencerede pişirilmiş kebap.' },
  { id: 'f187', title: 'Testi Kebap', icon: '🏺', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Testide pişirilmiş kebap.' },
  { id: 'f188', title: 'Tandır Kebap', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Tandırda pişirilmiş kebap.' },
  { id: 'f189', title: 'Çömlek Kebap', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Çömlekte pişirilmiş kebap.' },
  { id: 'f190', title: 'Güveç Kebap', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Güveçte pişirilmiş kebap.' },
  { id: 'f191', title: 'Sac Kavurma', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sac üzerinde pişirilmiş kavurma.' },
  { id: 'f192', title: 'Sac Tava', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sac üzerinde pişirilmiş tava.' },
  { id: 'f193', title: 'Sac Kebabı', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sac üzerinde pişirilmiş kebap.' },
  { id: 'f194', title: 'Sac Sote', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sac üzerinde pişirilmiş sote.' },
  { id: 'f195', title: 'Sac Yemek', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Sac üzerinde pişirilmiş yemek.' },
  { id: 'f196', title: 'Sac Kavurma (Kuzu)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kuzu etiyle yapılan sac kavurma.' },
  { id: 'f197', title: 'Sac Kavurma (Dana)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Dana etiyle yapılan sac kavurma.' },
  { id: 'f198', title: 'Sac Kavurma (Kıyma)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kıymayla yapılan sac kavurma.' },
  { id: 'f199', title: 'Sac Kavurma (Kuşbaşı)', icon: '🍖', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kuşbaşı etle yapılan sac kavurma.' },
  { id: 'f200', title: 'Sac Kavurma (Bonfile)', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Bonfile etle yapılan sac kavurma.' },

  // =================================================================
  // 🥘 EV YEMEĞİ & GELENEKSEL (Sıcak ve Samimi) - DEVAM
  // =================================================================
  { id: 'e61', title: 'Kuru Fasulye (Sulu)', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Bol sulu, tereyağlı.' },
  { id: 'e62', title: 'Kuru Fasulye (Kuru)', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Az sulu, daha kıvamlı.' },
  { id: 'e63', title: 'Kuru Fasulye (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e64', title: 'Kuru Fasulye (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e65', title: 'Kuru Fasulye (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e66', title: 'Kuru Fasulye (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e67', title: 'Barbunya Pilaki', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Zeytinyağlı, soğuk servis edilir.' },
  { id: 'e68', title: 'Barbunya (Sulu)', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Bol sulu, sıcak servis edilir.' },
  { id: 'e69', title: 'Barbunya (Kuru)', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Az sulu, daha kıvamlı.' },
  { id: 'e70', title: 'Barbunya (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e71', title: 'Barbunya (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e72', title: 'Barbunya (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e73', title: 'Barbunya (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e74', title: 'Nohut Yemeği', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Bol sulu, tereyağlı.' },
  { id: 'e75', title: 'Nohut (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e76', title: 'Nohut (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e77', title: 'Nohut (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e78', title: 'Nohut (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e79', title: 'Mercimek Yemeği', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Bol sulu, tereyağlı.' },
  { id: 'e80', title: 'Mercimek (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e81', title: 'Mercimek (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e82', title: 'Mercimek (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e83', title: 'Mercimek (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e84', title: 'Börülce Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Zeytinyağlı, soğuk servis edilir.' },
  { id: 'e85', title: 'Börülce (Sulu)', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Bol sulu, sıcak servis edilir.' },
  { id: 'e86', title: 'Börülce (Kuru)', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Az sulu, daha kıvamlı.' },
  { id: 'e87', title: 'Börülce (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e88', title: 'Börülce (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e89', title: 'Börülce (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e90', title: 'Börülce (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e91', title: 'Bezelye Yemeği', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Bol sulu, tereyağlı.' },
  { id: 'e92', title: 'Bezelye (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e93', title: 'Bezelye (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e94', title: 'Bezelye (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e95', title: 'Bezelye (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e96', title: 'Bamya Yemeği', icon: '🍲', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Bol sulu, limonlu.' },
  { id: 'e97', title: 'Bamya (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e98', title: 'Bamya (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e99', title: 'Bamya (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e100', title: 'Bamya (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e101', title: 'Karnabahar Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, limonlu.' },
  { id: 'e102', title: 'Karnabahar (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e103', title: 'Karnabahar (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e104', title: 'Karnabahar (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e105', title: 'Karnabahar (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e106', title: 'Brokoli Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, limonlu.' },
  { id: 'e107', title: 'Brokoli (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e108', title: 'Brokoli (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e109', title: 'Brokoli (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e110', title: 'Brokoli (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e111', title: 'Ispanak Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, limonlu.' },
  { id: 'e112', title: 'Ispanak (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e113', title: 'Ispanak (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e114', title: 'Ispanak (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e115', title: 'Ispanak (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e116', title: 'Pazı Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, limonlu.' },
  { id: 'e117', title: 'Pazı (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e118', title: 'Pazı (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e119', title: 'Pazı (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e120', title: 'Pazı (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e121', title: 'Semizotu Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, yoğurtlu.' },
  { id: 'e122', title: 'Semizotu (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e123', title: 'Semizotu (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e124', title: 'Semizotu (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e125', title: 'Semizotu (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e126', title: 'Ebegümeci Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, yoğurtlu.' },
  { id: 'e127', title: 'Ebegümeci (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e128', title: 'Ebegümeci (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e129', title: 'Ebegümeci (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e130', title: 'Ebegümeci (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e131', title: 'Labada Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, yoğurtlu.' },
  { id: 'e132', title: 'Labada (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e133', title: 'Labada (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e134', title: 'Labada (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e135', title: 'Labada (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e136', title: 'Kuzukulağı Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Ekşi, bol sulu.' },
  { id: 'e137', title: 'Kuzukulağı (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e138', title: 'Kuzukulağı (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e139', title: 'Kuzukulağı (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e140', title: 'Kuzukulağı (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e141', title: 'Isırgan Otu Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, yoğurtlu.' },
  { id: 'e142', title: 'Isırgan Otu (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e143', title: 'Isırgan Otu (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e144', title: 'Isırgan Otu (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e145', title: 'Isırgan Otu (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e146', title: 'Madımak Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, yoğurtlu.' },
  { id: 'e147', title: 'Madımak (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e148', title: 'Madımak (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e149', title: 'Madımak (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e150', title: 'Madımak (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e151', title: 'Evelik Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, yoğurtlu.' },
  { id: 'e152', title: 'Evelik (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e153', title: 'Evelik (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e154', title: 'Evelik (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e155', title: 'Evelik (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e156', title: 'Kenger Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, yoğurtlu.' },
  { id: 'e157', title: 'Kenger (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e158', title: 'Kenger (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e159', title: 'Kenger (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e160', title: 'Kenger (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e161', title: 'Hardal Otu Yemeği', icon: '🍲', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol sulu, yoğurtlu.' },
  { id: 'e162', title: 'Hardal Otu (Etli)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kuşbaşı etle pişmiş.' },
  { id: 'e163', title: 'Hardal Otu (Sucuklu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sucukla pişmiş.' },
  { id: 'e164', title: 'Hardal Otu (Pastırmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Pastırmayla pişmiş.' },
  { id: 'e165', title: 'Hardal Otu (Kavurmalı)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Kavurmayla pişmiş.' },
  { id: 'e166', title: 'Roka Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e167', title: 'Marul Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e168', title: 'Göbek Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e169', title: 'Kıvırcık Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e170', title: 'Domates Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e171', title: 'Biber Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e172', title: 'Soğan Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e173', title: 'Havuç Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e174', title: 'Turp Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e175', title: 'Kereviz Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu, zeytinyağlı.' },
  { id: 'e176', title: 'Patates Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Mayonezli, yoğurtlu.' },
  { id: 'e177', title: 'Mısır Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Mayonezli, yoğurtlu.' },
  { id: 'e178', title: 'Ton Balıklı Salata', icon: '🥗', tags: ['food', 'light', 'mid-budget', 'home'], description: 'Ton balığı, mısır, mayonez.' },
  { id: 'e179', title: 'Tavuklu Salata', icon: '🥗', tags: ['food', 'light', 'mid-budget', 'home'], description: 'Izgara tavuk, yeşillik.' },
  { id: 'e180', title: 'Kıymalı Salata', icon: '🥗', tags: ['food', 'light', 'mid-budget', 'home'], description: 'Kıyma, yeşillik.' },
  { id: 'e181', title: 'Sucuklu Salata', icon: '🥗', tags: ['food', 'light', 'mid-budget', 'home'], description: 'Sucuk, yeşillik.' },
  { id: 'e182', title: 'Pastırmalı Salata', icon: '🥗', tags: ['food', 'light', 'mid-budget', 'home'], description: 'Pastırma, yeşillik.' },
  { id: 'e183', title: 'Kavurmalı Salata', icon: '🥗', tags: ['food', 'light', 'mid-budget', 'home'], description: 'Kavurma, yeşillik.' },
  { id: 'e184', title: 'Peynirli Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Beyaz peynir, yeşillik.' },
  { id: 'e185', title: 'Zeytinli Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Zeytin, yeşillik.' },
  { id: 'e186', title: 'Cevizli Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Ceviz, yeşillik.' },
  { id: 'e187', title: 'Fındıklı Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Fındık, yeşillik.' },
  { id: 'e188', title: 'Bademli Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Badem, yeşillik.' },
  { id: 'e189', title: 'Narlı Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Nar, yeşillik.' },
  { id: 'e190', title: 'Üzümlü Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Üzüm, yeşillik.' },
  { id: 'e191', title: 'Elmalı Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Elma, yeşillik.' },
  { id: 'e192', title: 'Armutlu Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Armut, yeşillik.' },
  { id: 'e193', title: 'Şeftalili Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Şeftali, yeşillik.' },
  { id: 'e194', title: 'Kayısılı Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Kayısı, yeşillik.' },
  { id: 'e195', title: 'Muzlu Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Muz, yeşillik.' },
  { id: 'e196', title: 'Çilekli Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Çilek, yeşillik.' },
  { id: 'e197', title: 'Kirazlı Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Kiraz, yeşillik.' },
  { id: 'e198', title: 'Vişneli Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Vişne, yeşillik.' },
  { id: 'e199', title: 'Erikli Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'Erik, yeşillik.' },
  { id: 'e200', title: 'İncirli Salata', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home'], description: 'İncir, yeşillik.' },

  // =================================================================
  // 💎 LÜKS & KEYİF (Maaş Günü / Date) - DEVAM
  // =================================================================
  { id: 'l41', title: 'Truffle Makarna', icon: '🍝', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Trüf mantarı ile lezzet şöleni.' },
  { id: 'l42', title: 'Karabiber Soslu Bonfile', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Taze çekilmiş karabiber ve krema soslu.' },
  { id: 'l43', title: 'Istakoz Termidor', icon: '🦞', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Özel sos ve peynirle fırında.' },
  { id: 'l44', title: 'Kaviar ve Blini', icon: '🥞', tags: ['food', 'snack', 'high-budget', 'luxury'], description: 'Lüks bir rus atıştırmalığı.' },
  { id: 'l45', title: 'Fuğru', icon: '🍄', tags: ['food', 'snack', 'high-budget', 'luxury'], description: 'Kuzu göbeği mantarı.' },
  { id: 'l46', title: 'Kuzu Kapama', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Kuzu eti, soğan ve baharatlarla.' },
  { id: 'l47', title: 'Ördek Konfit', icon: '🦆', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Yağda pişirilmiş ördek butu.' },
  { id: 'l48', title: 'Kaz Ciğeri', icon: '🍖', tags: ['food', 'snack', 'high-budget', 'luxury'], description: 'Kaz ciğeri, elma ve soğanla.' },
  { id: 'l49', title: 'Bıldırcın', icon: '🐦', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Fırında veya ızgarada.' },
  { id: 'l50', title: 'Sülün', icon: '🐦', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Av eti sevenler için.' },
  { id: 'l51', title: 'Keklik', icon: '🐦', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Doğal ortamda yetişmiş.' },
  { id: 'l52', title: 'Bıldırcın Yumurtası', icon: '🥚', tags: ['food', 'snack', 'high-budget', 'luxury'], description: 'Küçük ama lezzetli.' },
  { id: 'l53', title: 'Deve Kuşu Yumurtası', icon: '🥚', tags: ['food', 'snack', 'high-budget', 'luxury'], description: 'Dev boyutlarda.' },
  { id: 'l54', title: 'Kaz Yumurtası', icon: '🥚', tags: ['food', 'snack', 'high-budget', 'luxury'], description: 'İri ve lezzetli.' },
  { id: 'l55', title: 'Ördek Yumurtası', icon: '🥚', tags: ['food', 'snack', 'high-budget', 'luxury'], description: 'Tavuk yumurtasından farklı.' },
  { id: 'l56', title: 'Böğürtlenli Ördek', icon: '🦆', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Böğürtlen soslu ördek göğsü.' },
  { id: 'l57', title: 'Narlı Kaz', icon: '🦆', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Nar soslu kaz göğsü.' },
  { id: 'l58', title: 'Vişneli Ördek', icon: '🦆', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Vişne soslu ördek butu.' },
  { id: 'l59', title: 'Portakallı Ördek', icon: '🦆', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Portakal soslu ördek göğsü.' },
  { id: 'l60', title: 'Limonlu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Limon soslu tavuk göğsü.' },
  { id: 'l61', title: 'Hardallı Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Hardal soslu tavuk butu.' },
  { id: 'l62', title: 'Ballı Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Bal soslu tavuk kanat.' },
  { id: 'l63', title: 'Acılı Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Acı soslu tavuk butu.' },
  { id: 'l64', title: 'Soyalı Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Soya soslu tavuk göğsü.' },
  { id: 'l65', title: 'Teriyaki Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Teriyaki soslu tavuk butu.' },
  { id: 'l66', title: 'Kremalı Mantarlı Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Krema ve mantar soslu tavuk göğsü.' },
  { id: 'l67', title: 'Pestolu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Pesto soslu tavuk butu.' },
  { id: 'l68', title: 'Domates Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Domates soslu tavuk göğsü.' },
  { id: 'l69', title: 'Biber Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Biber soslu tavuk butu.' },
  { id: 'l70', title: 'Soğan Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Soğan soslu tavuk göğsü.' },
  { id: 'l71', title: 'Sarımsak Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Sarımsak soslu tavuk butu.' },
  { id: 'l72', title: 'Zencefil Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Zencefil soslu tavuk göğsü.' },
  { id: 'l73', title: 'Zerdeçal Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Zerdeçal soslu tavuk butu.' },
  { id: 'l74', title: 'Köri Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Köri soslu tavuk göğsü.' },
  { id: 'l75', title: 'Kimyon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Kimyon soslu tavuk butu.' },
  { id: 'l76', title: 'Kekik Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Kekik soslu tavuk göğsü.' },
  { id: 'l77', title: 'Nane Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Nane soslu tavuk butu.' },
  { id: 'l78', title: 'Fesleğen Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Fesleğen soslu tavuk göğsü.' },
  { id: 'l79', title: 'Reyhan Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Reyhan soslu tavuk butu.' },
  { id: 'l80', title: 'Biberiye Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Biberiye soslu tavuk göğsü.' },
  { id: 'l81', title: 'Defne Yapraklı Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Defne yaprağı ile pişirilmiş.' },
  { id: 'l82', title: 'Adaçayı Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Adaçayı soslu tavuk butu.' },
  { id: 'l83', title: 'Kekik ve Limon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Kekik ve limon soslu tavuk göğsü.' },
  { id: 'l84', title: 'Sarımsak ve Limon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Sarımsak ve limon soslu tavuk butu.' },
  { id: 'l85', title: 'Zeytinyağlı ve Limon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Zeytinyağı ve limon soslu tavuk göğsü.' },
  { id: 'l86', title: 'Bal ve Hardal Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Bal ve hardal soslu tavuk butu.' },
  { id: 'l87', title: 'Bal ve Soya Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Bal ve soya soslu tavuk göğsü.' },
  { id: 'l88', title: 'Bal ve Zencefil Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Bal ve zencefil soslu tavuk butu.' },
  { id: 'l89', title: 'Bal ve Sarımsak Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Bal ve sarımsak soslu tavuk göğsü.' },
  { id: 'l90', title: 'Bal ve Limon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Bal ve limon soslu tavuk butu.' },
  { id: 'l91', title: 'Acı ve Bal Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Acı ve bal soslu tavuk göğsü.' },
  { id: 'l92', title: 'Acı ve Soya Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Acı ve soya soslu tavuk butu.' },
  { id: 'l93', title: 'Acı ve Sarımsak Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Acı ve sarımsak soslu tavuk göğsü.' },
  { id: 'l94', title: 'Acı ve Limon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Acı ve limon soslu tavuk butu.' },
  { id: 'l95', title: 'Acı ve Zencefil Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Acı ve zencefil soslu tavuk göğsü.' },
  { id: 'l96', title: 'Soya ve Sarımsak Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Soya ve sarımsak soslu tavuk butu.' },
  { id: 'l97', title: 'Soya ve Limon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Soya ve limon soslu tavuk göğsü.' },
  { id: 'l98', title: 'Soya ve Zencefil Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Soya ve zencefil soslu tavuk butu.' },
  { id: 'l99', title: 'Sarımsak ve Limon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Sarımsak ve limon soslu tavuk göğsü.' },
  { id: 'l100', title: 'Zencefil ve Limon Soslu Tavuk', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'luxury'], description: 'Zencefil ve limon soslu tavuk butu.' },

  // =================================================================
  // 🏠 AKTİVİTE - EVDE / TEMBEL (Chill Mode) - DEVAM
  // =================================================================
  { id: 'h61', title: 'Masaüstü Oyunları', icon: '🎲', tags: ['activity', 'lazy', 'home', 'group'], description: 'Monopoly, Tabu, Jenga gibi klasikler.' },
  { id: 'h62', title: 'Kart Oyunları', icon: '🃏', tags: ['activity', 'lazy', 'home', 'group'], description: 'Pişti, Batak, Poker, 101.' },
  { id: 'h63', title: 'Yapboz', icon: '🧩', tags: ['activity', 'lazy', 'home', 'solo'], description: '1000 parça ve üzeri zorlu yapbozlar.' },
  { id: 'h64', title: 'Model Yapımı', icon: '✈️', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Uçak, gemi, araba modelleri.' },
  { id: 'h65', title: 'Ev Dekorasyonu', icon: '🏠', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Yeni dekorasyon fikirleri denemek.' },
  { id: 'h66', title: 'Ev Temizliği', icon: '🧹', tags: ['activity', 'energetic', 'home', 'solo'], description: 'Derinlemesine temizlik.' },
  { id: 'h67', title: 'Ev Düzenlemesi', icon: '📦', tags: ['activity', 'energetic', 'home', 'solo'], description: 'Eşyaları yer değiştirmek.' },
  { id: 'h68', title: 'Kıyafet Ayıklama', icon: '👕', tags: ['activity', 'energetic', 'home', 'solo'], description: 'Kullanılmayan kıyafetleri ayırmak.' },
  { id: 'h69', title: 'Kitap Okuma', icon: '📚', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Sessiz bir köşede kitap keyfi.' },
  { id: 'h70', title: 'Günlük Yazma', icon: '📔', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Duygu ve düşünceleri kağıda dökmek.' },
  { id: 'h71', title: 'Şiir Yazma', icon: '📝', tags: ['activity', 'lazy', 'home', 'solo'], description: 'İlham perisini çağırmak.' },
  { id: 'h72', title: 'Resim Yapma', icon: '🎨', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Suluboya, yağlıboya, karakalem.' },
  { id: 'h73', title: 'Müzik Dinleme', icon: '🎵', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Kulaklıkla kendi dünyana çekilmek.' },
  { id: 'h74', title: 'Enstrüman Çalma', icon: '🎸', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Gitar, piyano, bağlama.' },
  { id: 'h75', title: 'Şarkı Söyleme', icon: '🎤', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Karaoke yapmak.' },
  { id: 'h76', title: 'Dans Etme', icon: '💃', tags: ['activity', 'energetic', 'home', 'solo'], description: 'Müziğin ritmine kendini bırakmak.' },
  { id: 'h77', title: 'Meditasyon', icon: '🧘', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Zihni boşaltmak, rahatlamak.' },
  { id: 'h78', title: 'Yoga', icon: '🧘', tags: ['activity', 'energetic', 'home', 'solo'], description: 'Esneklik ve güç kazanmak.' },
  { id: 'h79', title: 'Pilates', icon: '🤸', tags: ['activity', 'energetic', 'home', 'solo'], description: 'Vücut kondisyonunu artırmak.' },
  { id: 'h80', title: 'Evde Spor', icon: '🏋️', tags: ['activity', 'energetic', 'home', 'solo'], description: 'Ağırlık kaldırmak, mekik çekmek.' },
  { id: 'h81', title: 'Dans Videoları İzleme', icon: '💃', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Yeni dans hareketleri öğrenmek.' },
  { id: 'h82', title: 'Yemek Videoları İzleme', icon: '🍳', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Yemek tarifleri izlemek.' },
  { id: 'h83', title: 'Belgesel İzleme', icon: '📺', tags: ['activity', 'lazy', 'home', 'solo'], description: 'National Geographic, Discovery.' },
  { id: 'h84', title: 'Komedi İzleme', icon: '📺', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Stand-up gösterileri.' },
  { id: 'h85', title: 'Dizi İzleme', icon: '📺', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Yeni sezonları kaçırmamak.' },
  { id: 'h86', title: 'Film İzleme', icon: '📺', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Sinema keyfi evde.' },
  { id: 'h87', title: 'Çizgi Film İzleme', icon: '📺', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Çocukluk çağrışımları.' },
  { id: 'h88', title: 'Anime İzleme', icon: '📺', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Japon animasyonları.' },
  { id: 'h89', title: 'Video Oyunu Oynama', icon: '🎮', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Bilgisayar veya konsol oyunları.' },
  { id: 'h90', title: 'Mobil Oyun Oynama', icon: '📱', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Telefonda oyun oynamak.' },
  { id: 'h91', title: 'Sosyal Medya Gezintisi', icon: '📱', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Instagram, TikTok, Twitter.' },
  { id: 'h92', title: 'Alışveriş Siteleri Gezme', icon: '🛒', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Online alışveriş yapmak.' },
  { id: 'h93', title: 'Blog Yazma', icon: '📝', tags: ['activity', 'lazy', 'home', 'solo'], description: 'İlgi alanları hakkında yazılar yazmak.' },
  { id: 'h94', title: 'Vlog Çekme', icon: '📹', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Video blog hazırlamak.' },
  { id: 'h95', title: 'Podcast Hazırlama', icon: '🎙️', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Ses kaydı yapmak.' },
  { id: 'h96', title: 'Fotoğraf Düzenleme', icon: '📸', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Photoshop, Lightroom.' },
  { id: 'h97', title: 'Video Düzenleme', icon: '🎬', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Premiere Pro, Final Cut.' },
  { id: 'h98', title: 'Müzik Prodüksiyonu', icon: '🎵', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Kendi müziğini yapmak.' },
  { id: 'h99', title: 'Yemek Pişirme', icon: '🍳', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Yeni tarifler denemek.' },
  { id: 'h100', title: 'Fırın Keyfi', icon: '🍪', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Kurabiye, kek, börek yapmak.' },

  // =================================================================
  // 🌳 AKTİVİTE - DIŞARI / SOSYAL (Gezme Tozma) - DEVAM
  // =================================================================
  { id: 'o81', title: 'Alışveriş Merkezi', icon: '🛍️', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Mağazaları gezmek.' },
  { id: 'o82', title: 'Kitapçı', icon: '📚', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Yeni kitaplar keşfetmek.' },
  { id: 'o83', title: 'Müze', icon: '🏛️', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Tarih ve sanat.' },
  { id: 'o84', title: 'Sergi', icon: '🖼️', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Sanat eserlerini incelemek.' },
  { id: 'o85', title: 'Hayvanat Bahçesi', icon: '🐘', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Hayvanları gözlemlemek.' },
  { id: 'o86', title: 'Botanik Bahçe', icon: '🌳', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Bitkileri incelemek.' },
  { id: 'o87', title: 'Akvaryum', icon: '🐠', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Deniz canlılarını izlemek.' },
  { id: 'o88', title: 'Planetaryum', icon: '🌌', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Yıldızları izlemek.' },
  { id: 'o89', title: 'Gözlemevi', icon: '🔭', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Teleskopla gökyüzünü incelemek.' },
  { id: 'o90', title: 'Kütüphane', icon: '📚', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Sessiz ortamda ders çalışmak.' },
  { id: 'o91', title: 'Kafe', icon: '☕', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Kahve içip kitap okumak.' },
  { id: 'o92', title: 'Pastane', icon: '🍰', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Tatlı yemek.' },
  { id: 'o93', title: 'Restoran', icon: '🍽️', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Yemek yemek.' },
  { id: 'o94', title: 'Fast Food', icon: '🍔', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Hızlı yemek.' },
  { id: 'o95', title: 'Büfe', icon: '🌭', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Atıştırmalık almak.' },
  { id: 'o96', title: 'Market', icon: '🛒', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Alışveriş yapmak.' },
  { id: 'o97', title: 'Pazar', icon: '🍅', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Taze sebze meyve almak.' },
  { id: 'o98', title: 'Manav', icon: '🍎', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Meyve sebze almak.' },
  { id: 'o99', title: 'Kasap', icon: '🍖', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Et almak.' },
  { id: 'o100', title: 'Balıkçı', icon: '🐟', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Balık almak.' },
  { id: 'o101', title: 'Kuruyemişçi', icon: '🥜', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Kuruyemiş almak.' },
  { id: 'o102', title: 'Şarküteri', icon: '🧀', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Peynir, zeytin almak.' },
  { id: 'o103', title: 'Fırın', icon: '🥖', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Ekmek almak.' },
  { id: 'o104', title: 'Tatlıcı', icon: '🍮', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tatlı almak.' },
  { id: 'o105', title: 'Dondurmacı', icon: '🍦', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Dondurma yemek.' },
  { id: 'o106', title: 'Simitçi', icon: '🥯', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Simit almak.' },
  { id: 'o107', title: 'Kestaneci', icon: '🌰', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Kestane almak.' },
  { id: 'o108', title: 'Mısırcı', icon: '🌽', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Mısır almak.' },
  { id: 'o109', title: 'Macera Parkı', icon: '🌲', tags: ['activity', 'energetic', 'outdoor', 'solo'], description: 'Doğa sporları yapmak.' },
  { id: 'o110', title: 'Kayak Merkezi', icon: '⛷️', tags: ['activity', 'energetic', 'outdoor', 'solo'], description: 'Kayak yapmak.' },
  { id: 'o111', title: 'Snowboard Parkı', icon: '🏂', tags: ['activity', 'energetic', 'outdoor', 'solo'], description: 'Snowboard yapmak.' },
  { id: 'o112', title: 'Yüzme Havuzu', icon: '🏊', tags: ['activity', 'energetic', 'indoor', 'solo'], description: 'Yüzmek.' },
  { id: 'o113', title: 'Plaj', icon: '🏖️', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Güneşlenmek.' },
  { id: 'o114', title: 'Göl', icon: '🌅', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Doğa yürüyüşü.' },
  { id: 'o115', title: 'Nehir', icon: '🌊', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tekne turu.' },
  { id: 'o116', title: 'Şelale', icon: '💦', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Doğa manzarası.' },
  { id: 'o117', title: 'Dağ', icon: '⛰️', tags: ['activity', 'energetic', 'outdoor', 'solo'], description: 'Tırmanış.' },
  { id: 'o118', title: 'Tepe', icon: '🌄', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Manzara izlemek.' },
  { id: 'o119', title: 'Vadi', icon: '🏞️', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Doğa yürüyüşü.' },
  { id: 'o120', title: 'Mağara', icon: '🕳️', tags: ['activity', 'energetic', 'outdoor', 'solo'], description: 'Mağara keşfi.' },
  { id: 'o121', title: 'Antik Kent', icon: '🏛️', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi eserleri incelemek.' },
  { id: 'o122', title: 'Kale', icon: '🏰', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarih turu.' },
  { id: 'o123', title: 'Camii', icon: '🕌', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Mimariyi incelemek.' },
  { id: 'o124', title: 'Kilise', icon: '⛪', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi yapı.' },
  { id: 'o125', title: 'Sinagog', icon: '🕍', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Kültürel miras.' },
  { id: 'o126', title: 'Mabet', icon: '🙏', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'İbadet etmek.' },
  { id: 'o127', title: 'Tapınak', icon: '🛕', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi kalıntı.' },
  { id: 'o128', title: 'Anıt', icon: '🗽', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi değer.' },
  { id: 'o129', title: 'Heykel', icon: '🗿', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Sanat eseri.' },
  { id: 'o130', title: 'Çeşme', icon: '⛲', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi çeşme.' },
  { id: 'o131', title: 'Köprü', icon: '🌉', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Mimari yapı.' },
  { id: 'o132', title: 'Kule', icon: '🗼', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Manzara seyretmek.' },
  { id: 'o133', title: 'Saat Kulesi', icon: '⏰', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi saat.' },
  { id: 'o134', title: 'Çan Kulesi', icon: '🔔', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi çan.' },
  { id: 'o135', title: 'Medrese', icon: '📚', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi eğitim yapısı.' },
  { id: 'o136', title: 'Han', icon: '🏨', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi konaklama yapısı.' },
  { id: 'o137', title: 'Kervansaray', icon: '🐫', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi ticaret yapısı.' },
  { id: 'o138', title: 'Bedesten', icon: '🛍️', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi çarşı.' },
  { id: 'o139', title: 'Arasta', icon: '🛒', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarihi dükkanlar.' },
  { id: 'o140', title: 'Çarşı', icon: '🛍️', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Alışveriş yapmak.' },
  { id: 'o141', title: 'Pazar Yeri', icon: '🍅', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Taze ürünler almak.' },
  { id: 'o142', title: 'Bit Pazarı', icon: '🕰️', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Antika eşya aramak.' },
  { id: 'o143', title: 'Kitap Fuarı', icon: '📚', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Yeni kitaplar keşfetmek.' },
  { id: 'o144', title: 'Sanat Fuarı', icon: '🎨', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Sanat eserlerini incelemek.' },
  { id: 'o145', title: 'Teknoloji Fuarı', icon: '📱', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Yeni teknolojileri görmek.' },
  { id: 'o146', title: 'Otomobil Fuarı', icon: '🚗', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Yeni modelleri incelemek.' },
  { id: 'o147', title: 'Motosiklet Fuarı', icon: '🏍️', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Motosiklet meraklıları için.' },
  { id: 'o148', title: 'Yat Fuarı', icon: '⛵', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Lüks yaşam.' },
  { id: 'o149', title: 'Uçak Fuarı', icon: '✈️', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Havacılık meraklıları için.' },
  { id: 'o150', title: 'Savunma Sanayi Fuarı', icon: '🛡️', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Askeri teknolojiler.' },
  { id: 'o151', title: 'Tarım Fuarı', icon: '🚜', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Tarım teknolojileri.' },
  { id: 'o152', title: 'Hayvancılık Fuarı', icon: '🐄', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Hayvan yetiştiriciliği.' },
  { id: 'o153', title: 'Gıda Fuarı', icon: '🍕', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Yeni lezzetler keşfetmek.' },
  { id: 'o154', title: 'İçecek Fuarı', icon: '🍷', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Alkollü ve alkolsüz içecekler.' },
  { id: 'o155', title: 'Tatlı Fuarı', icon: '🍮', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Tatlı çeşitleri.' },
  { id: 'o156', title: 'Kahve Fuarı', icon: '☕', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Kahve çeşitleri.' },
  { id: 'o157', title: 'Çay Fuarı', icon: '🍵', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Çay çeşitleri.' },
  { id: 'o158', title: 'Baharat Fuarı', icon: '🌶️', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Baharat çeşitleri.' },
  { id: 'o159', title: 'Zeytinyağı Fuarı', icon: '🫒', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Zeytinyağı çeşitleri.' },
  { id: 'o160', title: 'Bal Fuarı', icon: '🍯', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Bal çeşitleri.' },
  { id: 'o161', title: 'Peynir Fuarı', icon: '🧀', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Peynir çeşitleri.' },
  { id: 'o162', title: 'Zeytin Fuarı', icon: '🫒', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Zeytin çeşitleri.' },
  { id: 'o163', title: 'Şarap Fuarı', icon: '🍷', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Şarap çeşitleri.' },
  { id: 'o164', title: 'Bira Fuarı', icon: '🍺', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Bira çeşitleri.' },
  { id: 'o165', title: 'Rakı Fuarı', icon: '🥃', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Rakı çeşitleri.' },
  { id: 'o166', title: 'Votka Fuarı', icon: '🥃', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Votka çeşitleri.' },
  { id: 'o167', title: 'Viski Fuarı', icon: '🥃', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Viski çeşitleri.' },
  { id: 'o168', title: 'Konyak Fuarı', icon: '🥃', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Konyak çeşitleri.' },
  { id: 'o169', title: 'Şampanya Fuarı', icon: '🍾', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Şampanya çeşitleri.' },
  { id: 'o170', title: 'Likör Fuarı', icon: '🍸', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Likör çeşitleri.' },
  { id: 'o171', title: 'Kokteyl Fuarı', icon: '🍹', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Kokteyl çeşitleri.' },
  { id: 'o172', title: 'Meyve Suyu Fuarı', icon: '🍹', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Meyve suyu çeşitleri.' },
  { id: 'o173', title: 'Smoothie Fuarı', icon: '🥤', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Smoothie çeşitleri.' },
  { id: 'o174', title: 'Milkshake Fuarı', icon: '🥤', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Milkshake çeşitleri.' },
  { id: 'o175', title: 'Dondurma Fuarı', icon: '🍦', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Dondurma çeşitleri.' },
  { id: 'o176', title: 'Pastane Fuarı', icon: '🍰', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Pastane ürünleri.' },
  { id: 'o177', title: 'Fırın Fuarı', icon: '🥖', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Fırın ürünleri.' },
  { id: 'o178', title: 'Restoran Fuarı', icon: '🍽️', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Restoran çeşitleri.' },
  { id: 'o179', title: 'Kafe Fuarı', icon: '☕', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Kafe çeşitleri.' },
  { id: 'o180', title: 'Fast Food Fuarı', icon: '🍔', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Fast food çeşitleri.' },
  { id: 'o181', title: 'Street Food Fuarı', icon: '🌮', tags: ['activity', 'lazy', 'outdoor', 'solo'], description: 'Sokak lezzetleri.' },
  { id: 'o182', title: 'Gurme Fuarı', icon: '🍴', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Gurme lezzetler.' },
  { id: 'o183', title: 'Organik Ürünler Fuarı', icon: '🌱', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Organik gıdalar.' },
  { id: 'o184', title: 'Vegan Ürünler Fuarı', icon: '🥦', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Vegan gıdalar.' },
  { id: 'o185', title: 'Vejetaryen Ürünler Fuarı', icon: '🥕', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Vejetaryen gıdalar.' },
  { id: 'o186', title: 'Glutensiz Ürünler Fuarı', icon: '🌾', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Glutensiz gıdalar.' },
  { id: 'o187', title: 'Laktozsuz Ürünler Fuarı', icon: '🥛', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Laktozsuz gıdalar.' },
  { id: 'o188', title: 'Şekersiz Ürünler Fuarı', icon: '🍬', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Şekersiz gıdalar.' },
  { id: 'o189', title: 'Diyet Ürünler Fuarı', icon: '🥗', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Diyet gıdalar.' },
  { id: 'o190', title: 'Sporcu Gıdaları Fuarı', icon: '💪', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Sporcu besinleri.' },
  { id: 'o191', title: 'Sağlıklı Yaşam Fuarı', icon: '🏥', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Sağlıklı ürünler.' },
  { id: 'o192', title: 'Doğal Ürünler Fuarı', icon: '🌿', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Doğal gıdalar.' },
  { id: 'o193', title: 'Kozmetik Fuarı', icon: '💄', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Kozmetik ürünleri.' },
  { id: 'o194', title: 'Parfüm Fuarı', icon: '🌸', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Parfüm çeşitleri.' },
  { id: 'o195', title: 'Makyaj Fuarı', icon: '💋', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Makyaj ürünleri.' },
  { id: 'o196', title: 'Cilt Bakımı Fuarı', icon: '🧴', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Cilt bakım ürünleri.' },
  { id: 'o197', title: 'Saç Bakımı Fuarı', icon: '💇', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Saç bakım ürünleri.' },
  { id: 'o198', title: 'Vücut Bakımı Fuarı', icon: '🛁', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Vücut bakım ürünleri.' },
  { id: 'o199', title: 'Ağız Bakımı Fuarı', icon: '🦷', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Ağız bakım ürünleri.' },
  { id: 'o200', title: 'El Bakımı Fuarı', icon: '💅', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'El bakım ürünleri.' },

  // =================================================================
  // 🎮 E-SPOR & OYUN (Gaming Zone)
  // =================================================================
  { id: 'g1', title: 'Valorant', icon: '🎯', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Taktiksel FPS, rank atlama zamanı.' },
  { id: 'g2', title: 'Counter-Strike 2', icon: '🔫', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Klasik FPS, eco round stratejileri.' },
  { id: 'g3', title: 'League of Legends', icon: '⚔️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'MOBA, feedleyenleri reportla.' },
  { id: 'g4', title: 'Dota 2', icon: '🗡️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Zorlu MOBA, carry olma vakti.' },
  { id: 'g5', title: 'Fortnite', icon: '🏹', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Battle Royale, dansları unutma.' },
  { id: 'g6', title: 'PUBG', icon: '🎖️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Gerçekçi Battle Royale, chicken dinner.' },
  { id: 'g7', title: 'Call of Duty: Warzone', icon: '🎮', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Hızlı tempolu Battle Royale.' },
  { id: 'g8', title: 'Apex Legends', icon: '🚀', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Hareketli Battle Royale, legend seçimi.' },
  { id: 'g9', title: 'Overwatch 2', icon: '🛡️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Takım tabanlı FPS, role uyum.' },
  { id: 'g10', title: 'Rainbow Six Siege', icon: '🔍', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Taktiksel FPS, duvar yıkma stratejileri.' },
  { id: 'g11', title: 'Minecraft', icon: '⛏️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Yaratıcılık, survival modda hayatta kal.' },
  { id: 'g12', title: 'GTA V Online', icon: '🚓', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Açık dünya, heist planlama.' },
  { id: 'g13', title: 'Red Dead Redemption 2', icon: '🐎', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Western macerası, doğa keşfi.' },
  { id: 'g14', title: 'Elden Ring', icon: '💍', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Zorlu RPG, boss fight stresi.' },
  { id: 'g15', title: 'Dark Souls Serisi', icon: '🔥', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Zorun sevenler için, rage quit riski.' },
  { id: 'g16', title: 'Cyberpunk 2077', icon: '🔮', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Cyberpunk RPG, Night City keşfi.' },
  { id: 'g17', title: 'The Witcher 3', icon: '🐺', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Epik RPG, Gwent turnuvaları.' },
  { id: 'g18', title: 'FIFA 24', icon: '⚽', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Futbol simülasyonu, Ultimate Team.' },
  { id: 'g19', title: 'NBA 2K24', icon: '🏀', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Basketbol simülasyonu, MyCareer.' },
  { id: 'g20', title: 'Rocket League', icon: '🚗', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Araba futbolu, aerial şovları.' },
  { id: 'g21', title: 'Among Us', icon: '👨‍🚀', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Sosyal dedüksiyon, impostor olma.' },
  { id: 'g22', title: 'Fall Guys', icon: '🤹', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Eğlenceli yarışma, engelleri aş.' },
  { id: 'g23', title: 'Stardew Valley', icon: '🚜', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Çiftlik simülasyonu, romantik ilişkiler.' },
  { id: 'g24', title: 'Animal Crossing', icon: '🏝️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Sakin ada yaşamı, balık tutma.' },
  { id: 'g25', title: 'Hearthstone', icon: '🃏', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Kart koleksiyonu, deck stratejileri.' },
  { id: 'g26', title: 'Magic: The Gathering Arena', icon: '✨', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Stratejik kart oyunu, mana dengesi.' },
  { id: 'g27', title: 'World of Warcraft', icon: '🌍', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'MMORPG, raid hazırlıkları.' },
  { id: 'g28', title: 'Final Fantasy XIV', icon: '🎭', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'MMORPG, hikaye odaklı.' },
  { id: 'g29', title: 'Genshin Impact', icon: '🌄', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Açık dünya RPG, gacha sistem.' },
  { id: 'g30', title: 'Honkai: Star Rail', icon: '🚂', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Uzay macerası, turn-based savaş.' },
  { id: 'g31', title: 'Diablo IV', icon: '😈', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Aksiyon RPG, loot avı.' },
  { id: 'g32', title: 'Path of Exile', icon: '🕸️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Karmaşık skill tree, build çeşitliliği.' },
  { id: 'g33', title: 'Baldur s Gate 3', icon: '🐉', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'D&D tabanlı RPG, taktiksel savaş.' },
  { id: 'g34', title: 'Starfield', icon: '🪐', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Uzay keşfi, gezegenler arası yolculuk.' },
  { id: 'g35', title: 'No Man s Sky', icon: '🌌', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Prosedürel evren, sonsuz keşif.' },
  { id: 'g36', title: 'Terraria', icon: '🪓', tags: ['activity', 'lazy', 'home', 'gaming'], description: '2D sandbox, boss savaşları.' },
  { id: 'g37', title: 'Rust', icon: '🦀', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Hayatta kalma, base inşa etme.' },
  { id: 'g38', title: 'Ark: Survival Evolved', icon: '🦖', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Dinozorlarla hayatta kalma, taming.' },
  { id: 'g39', title: 'Sea of Thieves', icon: '🏴‍☠️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Korsan simülasyonu, hazine avı.' },
  { id: 'g40', title: 'Monster Hunter: World', icon: '🐲', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Dev canavarları avlama, ekipman yapımı.' },
  { id: 'g41', title: 'Persona 5 Royal', icon: '🎭', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'J-RPG, sosyal bağ kurma.' },
  { id: 'g42', title: 'Yakuza Serisi', icon: '🗾', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Aksiyon-drama, mini oyunlar.' },
  { id: 'g43', title: 'Resident Evil 4 Remake', icon: '🧟', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Survival horror, korku dolu anlar.' },
  { id: 'g44', title: 'Dead by Daylight', icon: '🔪', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Asimetrik korku, katil veya survivor.' },
  { id: 'g45', title: 'Phasmophobia', icon: '👻', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Paranormal araştırma, hayalet avı.' },
  { id: 'g46', title: 'Destiny 2', icon: '🌠', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Looter shooter, raid ve dungeon.' },
  { id: 'g47', title: 'Warframe', icon: '🛡️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Uzay ninjaları, hızlı tempolu savaş.' },
  { id: 'g48', title: 'Borderlands 3', icon: '🔫', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Looter shooter, mizah dolu hikaye.' },
  { id: 'g49', title: 'The Elder Scrolls V: Skyrim', icon: '🐉', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Açık dünya RPG, modlama cenneti.' },
  { id: 'g50', title: 'Mass Effect Legendary Edition', icon: '🚀', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Uzay operası, kararların önemi.' },
  { id: 'g51', title: 'Divinity: Original Sin 2', icon: '⚔️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Taktiksel RPG, element etkileşimleri.' },
  { id: 'g52', title: 'XCOM 2', icon: '👽', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Taktiksel savaş, %99 isabet miss.' },
  { id: 'g53', title: 'Civilization VI', icon: '🏛️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Sıra tabanlı strateji, medeniyet kurma.' },
  { id: 'g54', title: 'Crusader Kings III', icon: '👑', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Hanedan simülasyonu, politika ve savaş.' },
  { id: 'g55', title: 'Cities: Skylines', icon: '🏙️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Şehir inşa etme, trafik çözümleri.' },
  { id: 'g56', title: 'The Sims 4', icon: '🏠', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Yaşam simülasyonu, karakter yaratma.' },
  { id: 'g57', title: 'Planet Zoo', icon: '🐯', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Hayvanat bahçesi inşa etme, tür koruma.' },
  { id: 'g58', title: 'Euro Truck Simulator 2', icon: '🚚', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Tır simülasyonu, Avrupa turu.' },
  { id: 'g59', title: 'Microsoft Flight Simulator', icon: '✈️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Gerçekçi uçuş simülasyonu, dünya turu.' },
  { id: 'g60', title: 'Forza Horizon 5', icon: '🏎️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Açık dünya yarış, Meksika manzaraları.' },
  { id: 'g61', title: 'Gran Turismo 7', icon: '🏁', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Realistik yarış simülasyonu.' },
  { id: 'g62', title: 'iRacing', icon: '🏎️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Profesyonel yarış simülasyonu.' },
  { id: 'g63', title: 'Assetto Corsa Competizione', icon: '🚗', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'GT yarış simülasyonu, fizik motoru.' },
  { id: 'g64', title: 'Project CARS 3', icon: '🏆', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Yarış simülasyonu, kariyer modu.' },
  { id: 'g65', title: 'Need for Speed Heat', icon: '🚓', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Arcade yarış, polis kovalamacası.' },
  { id: 'g66', title: 'Mortal Kombat 1', icon: '🥋', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Dövüş oyunu, fatality ler.' },
  { id: 'g67', title: 'Street Fighter 6', icon: '👊', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Klasik dövüş, yeni mekanikler.' },
  { id: 'g68', title: 'Tekken 8', icon: '🥊', tags: ['activity', 'lazy', 'home', 'gaming'], description: '3D dövüş, karakter hikayeleri.' },
  { id: 'g69', title: 'Super Smash Bros. Ultimate', icon: '🎮', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Nintendo karakterleri, çok oyunculu.' },
  { id: 'g70', title: 'Guilty Gear Strive', icon: '🎸', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Anime dövüş, rock müzik.' },
  { id: 'g71', title: 'Hollow Knight', icon: '🐛', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Metroidvania, zorlu platform.' },
  { id: 'g72', title: 'Celeste', icon: '🏔️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Zorlu platform, duygusal hikaye.' },
  { id: 'g73', title: 'Ori and the Blind Forest', icon: '🦌', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Görsel şölen, duygusal yolculuk.' },
  { id: 'g74', title: 'Cuphead', icon: '☕', tags: ['activity', 'lazy', 'home', 'gaming'], description: '1930 lar çizimi, zorlu boss savaşları.' },
  { id: 'g75', title: 'Hades', icon: '⚡', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Roguelike, Yunan mitolojisi.' },
  { id: 'g76', title: 'Dead Cells', icon: '💀', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Roguelike-metroidvania, hızlı tempolu.' },
  { id: 'g77', title: 'Returnal', icon: '🌌', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Roguelike, uzay macerası.' },
  { id: 'g78', title: 'Risk of Rain 2', icon: '🌧️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Roguelike, 3D savaş.' },
  { id: 'g79', title: 'Slay the Spire', icon: '🃏', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Roguelike deckbuilder, strateji.' },
  { id: 'g80', title: 'Inscryption', icon: '🪄', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Korku deckbuilder, sıra dışı hikaye.' },
  { id: 'g81', title: 'Outer Wilds', icon: '🪐', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Keşif oyunu, zaman döngüsü.' },
  { id: 'g82', title: 'Disco Elysium', icon: '🕵️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'RPG, dedektiflik, diyalog ağırlıklı.' },
  { id: 'g83', title: 'What Remains of Edith Finch', icon: '🏚️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Walking simulator, duygusal hikaye.' },
  { id: 'g84', title: 'Firewatch', icon: '🔥', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Doğa yürüyüşü, gizem.' },
  { id: 'g85', title: 'Gone Home', icon: '🏠', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Keşif, aile sırları.' },
  { id: 'g86', title: 'Life is Strange', icon: '🦋', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Görsel roman, zaman manipülasyonu.' },
  { id: 'g87', title: 'The Walking Dead', icon: '🧟', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Karar verme, duygusal bağ.' },
  { id: 'g88', title: 'Until Dawn', icon: '🏔️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Interactive drama, hayatta kalma.' },
  { id: 'g89', title: 'Detroit: Become Human', icon: '🤖', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Androidler, ahlaki ikilemler.' },
  { id: 'g90', title: 'Heavy Rain', icon: '🌧️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Gerilim, dedektiflik.' },
  { id: 'g91', title: 'Beyond: Two Souls', icon: '👻', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Paranormal, duygusal hikaye.' },
  { id: 'g92', title: 'The Last of Us Part I', icon: '🍄', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Survival, duygusal baba-kız hikayesi.' },
  { id: 'g93', title: 'The Last of Us Part II', icon: '🎻', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'İntikam, ahlaki sorgulamalar.' },
  { id: 'g94', title: 'God of War (2018)', icon: '🪓', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Baba-oğul yolculuğu, İskandinav mitolojisi.' },
  { id: 'g95', title: 'God of War Ragnarök', icon: '🌩️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Kıyamet, karakter gelişimi.' },
  { id: 'g96', title: 'Horizon Zero Dawn', icon: '🤖', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Mekanik canavarlar, açık dünya.' },
  { id: 'g97', title: 'Horizon Forbidden West', icon: '🌵', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Devam hikayesi, yeni tehditler.' },
  { id: 'g98', title: 'Spider-Man (2018)', icon: '🕷️', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Swing mekaniği, New York.' },
  { id: 'g99', title: 'Spider-Man: Miles Morales', icon: '⚡', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Yeni güçler, kişisel hikaye.' },
  { id: 'g100', title: 'Ghost of Tsushima', icon: '🎎', tags: ['activity', 'lazy', 'home', 'gaming'], description: 'Samuray, açık dünya, görsel şölen.' }
];

// SİHİRBAZ SORULARI (Değişmeden kalabilir, veri ile uyumlu)
export type QuestionType = {
  id: string;
  text: string;
  options: { label: string; value: string; nextStep: string | 'FINISH' }[];
};

export const WIZARD_STEPS: Record<string, QuestionType> = {
  'START': {
    id: 'step1',
    text: 'Selam Kardeşim! 👋\nBugün ortam nasıl?',
    options: [
      { label: 'Tek Tabancayım 🤠', value: 'solo', nextStep: 'MOOD_SOLO' },
      { label: 'Kankamla/Manitayla 👯', value: 'duo', nextStep: 'MOOD_GROUP' },
      { label: 'Aşiret Gibiyiz (Kalabalık) 🎉', value: 'group', nextStep: 'MOOD_GROUP' },
    ]
  },
  'MOOD_SOLO': {
    id: 'step2_solo',
    text: 'Peki, modun nasıl?',
    options: [
      { label: 'Kurt Gibi Açım 🐺', value: 'hungry', nextStep: 'BUDGET' },
      { label: 'Sıkıldım, Aktivite Lazım 🥱', value: 'bored', nextStep: 'ENERGY' },
      { label: 'Kafamı Dinleyeceğim 🧘', value: 'relax', nextStep: 'LOCATION_HOME' },
    ]
  },
  'MOOD_GROUP': {
    id: 'step2_group',
    text: 'Ekibin havası nasıl?',
    options: [
      { label: 'Herkes Açlıktan Ölüyor 🍕', value: 'hungry', nextStep: 'BUDGET' },
      { label: 'Eğlenmek İstiyoruz 🥳', value: 'fun', nextStep: 'ENERGY' },
      { label: 'Laklak Yapalım 🗣️', value: 'talk', nextStep: 'LOCATION_OUT' },
    ]
  },
  'BUDGET': {
    id: 'step3_budget',
    text: 'Cüzdanlar ne durumda?',
    options: [
      { label: 'Ay sonu (Öğrenci İşi) 💸', value: 'low-budget', nextStep: 'FINISH' },
      { label: 'Esnaf İşi (Orta) 💳', value: 'mid-budget', nextStep: 'FINISH' },
      { label: 'Maaş Yattı (Krallar Gibi) 👑', value: 'high-budget', nextStep: 'FINISH' },
    ]
  },
  'ENERGY': {
    id: 'step3_energy',
    text: 'Enerjiniz ne seviyede?',
    options: [
      { label: 'Pil bitik, yorma bizi 🪫', value: 'lazy', nextStep: 'LOCATION_HOME' },
      { label: 'Enerji tavan, uçarız! 🔋', value: 'energetic', nextStep: 'LOCATION_OUT' },
    ]
  },
  'LOCATION_HOME': {
    id: 'step4_home',
    text: 'Nerede takılmak istersin?',
    options: [
      { label: 'Evden çıkmam 🏠', value: 'home', nextStep: 'FINISH' },
      { label: 'Belki balkona çıkarız 🌇', value: 'home', nextStep: 'FINISH' },
    ]
  },
  'LOCATION_OUT': {
    id: 'step4_out',
    text: 'Mekan tercihin?',
    options: [
      { label: 'Açık hava olsun ☀️', value: 'outdoor', nextStep: 'FINISH' },
      { label: 'Kapalı mekan olsun 🏢', value: 'indoor', nextStep: 'FINISH' },
    ]
  }
};