// constants/masterData.ts

export type ItemType = {
  id: string;
  title: string;
  icon: string;
  tags: string[]; // Algoritma için anahtar kelimeler
  description: string;
};

export const MASTER_DATA: ItemType[] = [
  // =================================================================
  // 🌯 SOKAK LEZZETLERİ & FAST FOOD (Hızlı, Ucuz, Doyurucu)
  // =================================================================
  { id: 'f1', title: 'Tavuk Döner & Ayran', icon: '🌯', tags: ['food', 'hungry', 'low-budget', 'fast', 'student'], description: 'Bol soslu, çift lavaş, turşu yanında.' },
  { id: 'f2', title: 'Yarım Ekmek Kokoreç', icon: '🥖', tags: ['food', 'hungry', 'mid-budget', 'street', 'night'], description: 'İri kıyım, bol kimyonlu, çeyrek yetmez.' },
  { id: 'f3', title: 'Midye Dolma (30 Tane)', icon: '🦪', tags: ['food', 'snack', 'low-budget', 'street', 'group'], description: 'Limonu sık, durmadan göm. Saymayı bırak.' },
  { id: 'f4', title: 'Islak Hamburger', icon: '🍔', tags: ['food', 'snack', 'low-budget', 'street', 'fast'], description: 'Taksim usulü, en az 3 tane yenecek.' },
  { id: 'f5', title: 'Çiğ Köfte Dürüm', icon: '🍋', tags: ['food', 'hungry', 'low-budget', 'spicy', 'vegan'], description: 'Nar ekşisi sel olsun aksın, çift lavaş.' },
  { id: 'f6', title: 'Tavuk Pilav & Turşu', icon: '🍚', tags: ['food', 'hungry', 'low-budget', 'street', 'fast'], description: 'Seyyar arabadan, bol karabiberli.' },
  { id: 'f7', title: 'Ortaköy Kumpir', icon: '🥔', tags: ['food', 'hungry', 'mid-budget', 'outdoor'], description: 'İçine her malzemeden koydur, karıştır.' },
  { id: 'f8', title: 'Balık Ekmek', icon: '🐟', tags: ['food', 'hungry', 'low-budget', 'outdoor', 'view'], description: 'Eminönü havasında, bol soğanlı.' },
  { id: 'f9', title: 'Goralı / Sosisli', icon: '🌭', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Salçalı soslu klasik büfe lezzeti.' },
  { id: 'f10', title: 'Pide (Kuşbaşılı)', icon: '🥙', tags: ['food', 'hungry', 'mid-budget', 'group'], description: 'Kenarları kıtır, tereyağı üzerinde erisin.' },
  { id: 'f11', title: 'Lahmacun (Acılı)', icon: '🍕', tags: ['food', 'hungry', 'mid-budget', 'group'], description: 'İçine köz patlıcan koyup dür.' },
  { id: 'f12', title: 'Adana Dürüm', icon: '🌶️', tags: ['food', 'hungry', 'mid-budget', 'spicy'], description: 'Acısı sonradan çıkar, şalgamla iç.' },
  { id: 'f13', title: 'Çeşme Kumru', icon: '🥪', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Sayas peynirli, bol malzemeli.' },
  { id: 'f14', title: 'Tantuni (Yoğurtlu)', icon: '🌮', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Mersin ateşi, yağlı ve leziz. Çift lavaş.' },
  { id: 'f15', title: 'Arnavut Ciğeri', icon: '🧅', tags: ['food', 'hungry', 'mid-budget', 'street'], description: 'Sumaklı soğanla efsane olur.' },
  { id: 'f16', title: 'Boyoz & Yumurta', icon: '🥚', tags: ['food', 'snack', 'low-budget', 'morning'], description: 'İzmir kahvaltısının kralı.' },
  { id: 'f17', title: 'Gözleme & Çay', icon: '🥞', tags: ['food', 'snack', 'low-budget', 'cafe'], description: 'Patatesli, kaşarlı, otlu karışık.' },
  { id: 'f18', title: 'Kır Pidesi', icon: '🥟', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Sıcak sıcak, yanında soğuk meyve suyu.' },
  { id: 'f19', title: 'Sarıyer Böreği', icon: '🥧', tags: ['food', 'hungry', 'mid-budget', 'morning'], description: 'Çıtır çıtır, kıyması bol, yağı el yakar.' },
  { id: 'f20', title: 'Patso (Kaşarlı)', icon: '🍟', tags: ['food', 'hungry', 'low-budget', 'student'], description: 'Ekmek arası karbonhidrat şoku.' },
  { id: 'f21', title: 'Köfte Ekmek', icon: '🚌', tags: ['food', 'hungry', 'low-budget', 'street'], description: 'Maç çıkışı seyyar arabada.' },
  { id: 'f22', title: 'Taco & Nachos', icon: '🌮', tags: ['food', 'snack', 'mid-budget', 'group'], description: 'Meksika ateşi, guacamole soslu.' },
  { id: 'f23', title: 'Noodle Box', icon: '🥡', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Çin usulü, soya soslu, çubukla ye.' },
  { id: 'f24', title: 'Waffle', icon: '🧇', tags: ['food', 'dessert', 'mid-budget', 'cafe'], description: 'Meyve bombası, çikolata krizi.' },
  // --- YENİ EKLENEN SOKAK LEZZETLERİ & FAST FOOD (TR USULÜ) ---
  { id: 'f25', title: 'Sulu Köfte Sandviç', icon: '🥪', tags: ['food', 'hungry', 'low-budget', 'street'], description: 'Yanında bol acı biber turşusu ile.' },
  { id: 'f26', title: 'Ekmek Arası Sucuk', icon: '🌭', tags: ['food', 'hungry', 'low-budget', 'fast', 'street'], description: 'Izgaradan dumanı üstünde, bol ketçap mayonez.' },
  { id: 'f27', title: 'Tavuk Sote Dürüm', icon: '🌯', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Lavaş ince, tavuk sulu, soğan halkaları yanında.' },
  { id: 'f28', title: 'Tost (Karışık)', icon: '🥪', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Ayvalık usulü, bol kaşar, sucuk, domatesli.' },
  { id: 'f29', title: 'Mercimek Köftesi', icon: '🧆', tags: ['food', 'snack', 'low-budget', 'vegan', 'home'], description: 'Taze nane ve limon ile, marul yaprağına sarılı.' },
  { id: 'f30', title: 'Tavuklu Makarna (Kremalı)', icon: '🍝', tags: ['food', 'hungry', 'low-budget', 'student', 'home'], description: 'Pratik, doyurucu ve bol peynirli.' },
  { id: 'f31', title: 'Yağlama (Kayseri)', icon: '🥞', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kıymalı sosu bol, yoğurtlu.' },
  { id: 'f32', title: 'Ekmek Arası Ciğer', icon: '🥪', tags: ['food', 'hungry', 'mid-budget', 'street'], description: 'Güneydoğu usulü, bol maydanozlu.' },
  { id: 'f33', title: 'Pizza (İnce Hamur)', icon: '🍕', tags: ['food', 'hungry', 'mid-budget', 'fast', 'group'], description: 'Kenarları incecik, bol roka ile servis.' },
  { id: 'f34', title: 'Sokak Simidi & Çay', icon: '🥯', tags: ['food', 'snack', 'low-budget', 'street', 'morning'], description: 'Gevrek ve taze, yanında bir bardak demli çay.' },
  { id: 'f35', title: 'Kremalı Mantar Çorbası', icon: '🥣', tags: ['food', 'light', 'mid-budget', 'cafe'], description: 'Yanında kruton ekmekle iç ısıtır.' },
  { id: 'f36', title: 'Közde Mısır', icon: '🌽', tags: ['food', 'snack', 'low-budget', 'outdoor'], description: 'Bol tereyağlı ve tuzlu, sahil klasiği.' },
  { id: 'f37', title: 'Tavuklu Sezar Salata', icon: '🥗', tags: ['food', 'light', 'mid-budget', 'healthy'], description: 'Hafif ve doyurucu bir öğün.' },
  { id: 'f38', title: 'Sufle', icon: '🍫', tags: ['food', 'dessert', 'mid-budget', 'romance'], description: 'Ortası akışkan, dondurma ile servis.' },
  { id: 'f39', title: 'Makarna (Pesto Soslu)', icon: '🍝', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Taze fesleğen kokulu, parmesan peynirli.' },
  { id: 'f40', title: 'Boşnak Böreği', icon: '🥧', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kıymalı veya peynirli, çıtır çıtır.' },
  { id: 'f41', title: 'Dürüm Adana (Ciğerli)', icon: '🌯', tags: ['food', 'hungry', 'mid-budget', 'spicy', 'traditional'], description: 'Yanında köz soğan ve tırnak pide ile.' },
  { id: 'f42', title: 'Tantuni (Tarsus Usulü)', icon: '🌮', tags: ['food', 'hungry', 'mid-budget', 'fast', 'street'], description: 'Bol domates, soğan ve limon suyuyla ıslatılmış.' },
  { id: 'f43', title: 'Patates Kızartması & Ketçap', icon: '🍟', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Yanında soğuk ayran, dip sos şart.' },
  { id: 'f44', title: 'Tavuk Tantuni (Lavaş)', icon: '🌮', tags: ['food', 'hungry', 'low-budget', 'fast'], description: 'Limon ve maydanoz ikilisi.' },
  { id: 'f45', title: 'Gevrek (İzmir Simidi)', icon: '🥯', tags: ['food', 'snack', 'low-budget', 'morning', 'street'], description: 'Taze ve çıtır, yanında beyaz peynir.' },
  { id: 'f46', title: 'Turşu Suyu', icon: '🥒', tags: ['food', 'snack', 'low-budget', 'street'], description: 'Ankara, İzmir, İstanbul fark etmez, soksuyu candır.' },
  { id: 'f47', title: 'Büfe Köftesi', icon: '🍔', tags: ['food', 'hungry', 'low-budget', 'fast'], description: 'Basit ama lezzetli, bol yeşillikli.' },
  { id: 'f48', title: 'Külahta Dondurma', icon: '🍦', tags: ['food', 'dessert', 'low-budget', 'outdoor'], description: 'Maraş usulü, sakızlı veya sade.' },
  { id: 'f49', title: 'Közde Kestane', icon: '🌰', tags: ['food', 'snack', 'low-budget', 'street', 'outdoor'], description: 'Kış aylarının vazgeçilmezi.' },
  { id: 'f50', title: 'Balık Ekmek (Tekir)', icon: '🐟', tags: ['food', 'hungry', 'mid-budget', 'outdoor', 'view'], description: 'Galata Köprüsü klasiği.' },
  { id: 'f51', title: 'Midye Tava (Tarator Soslu)', icon: '🍤', tags: ['food', 'snack', 'mid-budget', 'street'], description: 'Bir porsiyon yetmez, sosuyla birlikte.' },
  { id: 'f52', title: 'Kayseri Mantısı (Sokak Versiyonu)', icon: '🥟', tags: ['food', 'hungry', 'low-budget', 'fast'], description: 'Küçük porsiyon, sarımsaklı yoğurtlu.' },
  { id: 'f53', title: 'Karışık Waffle', icon: '🧇', tags: ['food', 'dessert', 'mid-budget', 'cafe'], description: 'Çilek, muz, çikolata sosu, fındık...' },
  { id: 'f54', title: 'Süt Mısır', icon: '🌽', tags: ['food', 'snack', 'low-budget', 'outdoor'], description: 'Haşlanmış, bol tuzlu.' },
  { id: 'f55', title: 'Kumru (Sucuklu)', icon: '🥪', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Bol baharatlı sucuk ve kaşar.' },
  { id: 'f56', title: 'Tost (Yengen)', icon: '🥪', tags: ['food', 'hungry', 'low-budget', 'fast'], description: 'Sosis, salam, kaşar, domates...' },
  { id: 'f57', title: 'Pide (Peynirli)', icon: '🥙', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Sabah kahvaltısı için ideal.' },
  { id: 'f58', title: 'Sucuklu Yumurta (Ekmekle)', icon: '🍳', tags: ['food', 'hungry', 'low-budget', 'home', 'morning'], description: 'Kırmızı biberli, bol ekmek banmalık.' },
  { id: 'f59', title: 'Tavuklu Pilav Üstü Nohut', icon: '🍚', tags: ['food', 'hungry', 'low-budget', 'street'], description: 'Nohutsuz olmaz.' },
  { id: 'f60', title: 'Künefe (Fıstıklı)', icon: '🥞', tags: ['food', 'dessert', 'mid-budget', 'traditional'], description: 'Şerbeti sıcak, peyniri uzayan.' },
  { id: 'f61', title: 'Su Böreği (Kıymalı)', icon: '🥧', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kat kat, çıtır çıtır.' },
  { id: 'f62', title: 'Sütlaç (Fırın)', icon: '🍮', tags: ['food', 'dessert', 'low-budget', 'traditional'], description: 'Üstü yanık, tarçınlı.' },
  { id: 'f63', title: 'Dönerli Pide', icon: '🥙', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Pide arasında döner, soslu.' },
  { id: 'f64', title: 'Kır Pidesi (Kıymalı)', icon: '🥟', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Yanında domates, biber.' },
  { id: 'f65', title: 'Bükme (Ispanaklı)', icon: '🥬', tags: ['food', 'snack', 'low-budget', 'traditional'], description: 'Ev yapımı, bol tereyağlı.' },
  { id: 'f66', title: 'Sandviç (Salamlı Kaşarlı)', icon: '🥪', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Öğrenci klasiği.' },
  { id: 'f67', title: 'Taze Sıkılmış Meyve Suyu', icon: '🍊', tags: ['food', 'light', 'low-budget', 'healthy', 'outdoor'], description: 'Portakal veya nar suyu.' },
  { id: 'f68', title: 'Fıstık Ezmeli Ekmek', icon: '🥜', tags: ['food', 'snack', 'low-budget', 'home', 'fast'], description: 'Çocukluk tadı, hızlı enerji.' },
  { id: 'f69', title: 'Simit & Nutella', icon: '🥯', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Tatlı krizine pratik çözüm.' },
  { id: 'f70', title: 'Mercimek Çorbası (Ekmek Banmalı)', icon: '🥣', tags: ['food', 'hungry', 'low-budget', 'fast'], description: 'Limonlu, acı soslu.' },
  { id: 'f71', title: 'Kelle Paça Çorbası', icon: '🥣', tags: ['food', 'hungry', 'mid-budget', 'night', 'traditional'], description: 'Gece yarısı şifa kaynağı.' },
  { id: 'f72', title: 'Halka Tatlısı', icon: '🍩', tags: ['food', 'dessert', 'low-budget', 'street'], description: 'Şerbetli ve çıtır.' },
  { id: 'f73', title: 'Süt Burger', icon: '🍔', tags: ['food', 'snack', 'low-budget', 'fast'], description: 'Soğuk, çikolatalı atıştırmalık.' },
  { id: 'f74', title: 'Çay (Sınırsız)', icon: '☕', tags: ['food', 'relax', 'low-budget', 'cafe'], description: 'Keyifli sohbetlerin eşlikçisi.' },
  { id: 'f75', title: 'Şırdan (Adana)', icon: '🌶️', tags: ['food', 'hungry', 'mid-budget', 'street', 'spicy'], description: 'Sadece cesurlara.' },
  { id: 'f76', title: 'Tavuklu Wrap', icon: '🌯', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Izgara tavuklu, soslu, sebzeli.' },
  { id: 'f77', title: 'Dürüm (Vejetaryen)', icon: '🥗', tags: ['food', 'light', 'low-budget', 'vegan', 'fast'], description: 'Bol yeşillik ve sos.' },
  { id: 'f78', title: 'Peynirli Poğaça', icon: '🥐', tags: ['food', 'snack', 'low-budget', 'morning', 'cafe'], description: 'Taze ve yumuşak.' },
  { id: 'f79', title: 'Keten Tohumlu Salata', icon: '🥗', tags: ['food', 'light', 'high-budget', 'healthy'], description: 'Detoks zamanı.' },
  { id: 'f80', title: 'Kömbe (Hatay)', icon: '🥧', tags: ['food', 'snack', 'mid-budget', 'traditional'], description: 'İçinde hurma veya ceviz olan kurabiye.' },


  // =================================================================
  // 🥘 EV YEMEĞİ & GELENEKSEL (Sıcak ve Samimi)
  // =================================================================
  { id: 'e1', title: 'Kuru Fasulye & Pilav', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Milli ikilimiz, yanında turşu şart.' },
  { id: 'e2', title: 'Mantı', icon: '🥟', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Sarımsaklı yoğurt, naneli yağ sosu.' },
  { id: 'e3', title: 'Karnıyarık', icon: '🍆', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Patlıcanın en güzel hali, yanında cacık.' },
  { id: 'e4', title: 'Zeytinyağlı Sarma', icon: '🍇', tags: ['food', 'snack', 'mid-budget', 'home'], description: 'Limon sıkıp tencereyi bitir.' },
  { id: 'e5', title: 'Mercimek Köftesi', icon: '🧆', tags: ['food', 'snack', 'low-budget', 'home', 'group'], description: 'Günlerin vazgeçilmezi, marulla ye.' },
  { id: 'e6', title: 'Menemen', icon: '🍳', tags: ['food', 'hungry', 'low-budget', 'home', 'fast'], description: 'Soğanlı mı soğansız mı tartışmayın, ekmek banın.' },
  { id: 'e7', title: 'İskender Kebap', icon: '🥙', tags: ['food', 'hungry', 'high-budget', 'traditional'], description: 'Tereyağını üzerine cos diye döktür.' },
  { id: 'e8', title: 'Hünkar Beğendi', icon: '👑', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Saraylara layık, patlıcan yatağında et.' },
  { id: 'e9', title: 'Cağ Kebabı', icon: '🥩', tags: ['food', 'hungry', 'high-budget', 'traditional'], description: 'Erzurum usulü, şişleri sayma.' },
  { id: 'e10', title: 'Beyran Çorbası', icon: '🥣', tags: ['food', 'hungry', 'mid-budget', 'spicy'], description: 'Antep usulü, gribi söker atar.' },
  { id: 'e11', title: 'Tarhana Çorbası', icon: '🥄', tags: ['food', 'light', 'low-budget', 'home'], description: 'Anne eli değmiş gibi, şifa.' },
  { id: 'e12', title: 'Lahana Sarması', icon: '🥬', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Karadeniz usulü, yoğurtla.' },
  // --- YENİ EKLENEN EV YEMEĞİ & GELENEKSEL ---
  { id: 'e13', title: 'İzmir Köfte', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Bol sulu domatesli soslu, yanında püre.' },
  { id: 'e14', title: 'Pirinç Pilavı', icon: '🍚', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Tane tane, tereyağlı, ana yemeğin yancısı.' },
  { id: 'e15', title: 'Fasülye Diblesi', icon: '🥦', tags: ['food', 'light', 'mid-budget', 'home'], description: 'Karadeniz mutfağından, zeytinyağlı, hafif.' },
  { id: 'e16', title: 'Hamsi Tava', icon: '🐟', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Mısır ununa bulanmış, çıtır çıtır, deniz mevsimi!' },
  { id: 'e17', title: 'Güveç', icon: '🥘', tags: ['food', 'hungry', 'high-budget', 'traditional'], description: 'Toprak kapta, odun ateşinde pişmiş lezzet.' },
  { id: 'e18', title: 'Perde Pilavı (Siirt)', icon: '🍚', tags: ['food', 'hungry', 'high-budget', 'traditional'], description: 'Tavuklu ve bademli, özel günler için.' },
  { id: 'e19', title: 'Pırasa Yemeği', icon: '🥬', tags: ['food', 'light', 'low-budget', 'home'], description: 'Bol limonlu, zeytinyağlı ve sağlıklı.' },
  { id: 'e20', title: 'Pazar Kahvaltısı', icon: '🍳', tags: ['food', 'hungry', 'low-budget', 'home', 'morning'], description: 'Sıcacık demli çay, taze ekmek, peynir ve zeytin.' },
  { id: 'e21', title: 'Tavuk Suyu Çorbası', icon: '🥣', tags: ['food', 'light', 'low-budget', 'home'], description: 'Limonlu ve naneli, tam bir şifa kaynağı.' },
  { id: 'e22', title: 'Zeytinyağlı Enginar', icon: '🌿', tags: ['food', 'light', 'mid-budget', 'home', 'vegan'], description: 'Havuç ve bezelye dolgulu, lezzetli ve hafif.' },
  { id: 'e23', title: 'Ali Nazik Kebap', icon: '🍆', tags: ['food', 'hungry', 'high-budget', 'traditional'], description: 'Közlenmiş patlıcanlı yoğurt yatağında et.' },
  { id: 'e24', title: 'Keşkek (Trakya)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Düğün yemeği klasiği, bol tereyağlı.' },
  { id: 'e25', title: 'Börülce Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home', 'vegan'], description: 'Ege usulü, zeytinyağlı ve ekşili.' },
  { id: 'e26', title: 'Su Böreği', icon: '🥧', tags: ['food', 'snack', 'mid-budget', 'traditional'], description: 'Kat kat peynirli, yumuşacık lezzet.' },
  { id: 'e27', title: 'Aşure', icon: '🥣', tags: ['food', 'dessert', 'mid-budget', 'home', 'group'], description: 'Bol malzemeli, bolluk ve bereket simgesi.' },
  { id: 'e28', title: 'İçli Köfte (Haşlama)', icon: '🍘', tags: ['food', 'hungry', 'high-budget', 'traditional', 'home'], description: 'Haşlanmış, limonlu ve bol pul biberli.' },
  { id: 'e29', title: 'Taze Fasulye (Zeytinyağlı)', icon: '🌿', tags: ['food', 'light', 'low-budget', 'home', 'vegan'], description: 'Yanında cacık ve pirinç pilavı.' },
  { id: 'e30', title: 'Mercimek Köftesi (Kısırsız)', icon: '🧆', tags: ['food', 'snack', 'low-budget', 'home', 'group'], description: 'Taze soğanlı, limonlu, bol yeşillikli.' },
  { id: 'e31', title: 'Enginar Dolması', icon: '🍆', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Kıymalı veya zeytinyağlı.' },
  { id: 'e32', title: 'Kabak Çiçeği Dolması', icon: '🌼', tags: ['food', 'light', 'high-budget', 'home'], description: 'Hassas ve lezzetli Ege yemeği.' },
  { id: 'e33', title: 'Fırında Tavuk (Patatesli)', icon: '🍗', tags: ['food', 'hungry', 'mid-budget', 'home', 'group'], description: 'Sulu ve baharatlı, nar gibi kızarmış.' },
  { id: 'e34', title: 'Biber Dolması (Kıymalı)', icon: '🌶️', tags: ['food', 'hungry', 'mid-budget', 'home'], description: 'Yanında yoğurtla servis edilir.' },
  { id: 'e35', title: 'Mücver (Kabak)', icon: '🥒', tags: ['food', 'snack', 'low-budget', 'home', 'vegetarian'], description: 'Kızartılmış veya fırında, yoğurtlu soslu.' },
  { id: 'e36', title: 'Karalahana Çorbası', icon: '🥬', tags: ['food', 'hungry', 'low-budget', 'home', 'traditional'], description: 'Karadeniz usulü, bol mısır unlu.' },
  { id: 'e37', title: 'Pazar Kahvaltısı (Geniş)', icon: '🧀', tags: ['food', 'hungry', 'mid-budget', 'home', 'morning'], description: 'Uzun süren, keyifli kahvaltı.' },
  { id: 'e38', title: 'Kısır (Taze)', icon: '🥗', tags: ['food', 'snack', 'low-budget', 'home', 'group', 'vegan'], description: 'Gün menülerinin kraliçesi.' },
  { id: 'e39', title: 'Yaprak Sarma (Zeytinyağlı)', icon: '🍇', tags: ['food', 'snack', 'mid-budget', 'home', 'vegan'], description: 'Ekşili, limon dilimli.' },
  { id: 'e40', title: 'Karnabahar Yemeği', icon: '🥦', tags: ['food', 'light', 'low-budget', 'home'], description: 'Domatesli, sağlıklı.' },
  { id: 'e41', title: 'Ezo Gelin Çorbası', icon: '🥣', tags: ['food', 'light', 'low-budget', 'home'], description: 'Naneli, limonlu, acı biberli.' },
  { id: 'e42', title: 'Yoğurtlu Semizotu Salatası', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home', 'healthy'], description: 'Sarımsaklı, ferahlatıcı.' },
  { id: 'e43', title: 'Laz Böreği (Rize)', icon: '🥧', tags: ['food', 'dessert', 'mid-budget', 'traditional'], description: 'Şerbetli ve kremalı.' },
  { id: 'e44', title: 'Patates Oturtma', icon: '🥔', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Kıymalı harç ile fırında.' },
  { id: 'e45', title: 'Tavuklu Sandviç (Ev Yapımı)', icon: '🥪', tags: ['food', 'snack', 'low-budget', 'home', 'fast'], description: 'Taze ekmekle.' },
  { id: 'e46', title: 'Peynirli Tepsi Böreği', icon: '🥧', tags: ['food', 'hungry', 'mid-budget', 'home', 'group'], description: 'Bol peynir, tereyağlı.' },
  { id: 'e47', title: 'Aşure Günü', icon: '🥣', tags: ['food', 'dessert', 'mid-budget', 'home', 'group'], description: 'Bol meyveli, şekerli.' },
  { id: 'e48', title: 'Bulgur Pilavı (Domatesli)', icon: '🍚', tags: ['food', 'hungry', 'low-budget', 'home'], description: 'Salçalı, tereyağlı.' },
  { id: 'e49', title: 'Revani (Şerbetli Tatlı)', icon: '🍰', tags: ['food', 'dessert', 'low-budget', 'home'], description: 'Limon kabuklu, hafif şerbetli.' },
  { id: 'e50', title: 'Çoban Salata (Sirkeli)', icon: '🥗', tags: ['food', 'light', 'low-budget', 'home', 'vegan'], description: 'Kuru nane ve sumak olmazsa olmaz.' },
  { id: 'e51', title: 'Kuzu Tandır', icon: '🍖', tags: ['food', 'hungry', 'high-budget', 'traditional'], description: 'Ağızda dağılan et.' },
  { id: 'e52', title: 'Kömbe (Tuzlu)', icon: '🥧', tags: ['food', 'snack', 'mid-budget', 'traditional'], description: 'Kahvaltılık veya çay saati için.' },
  { id: 'e53', title: 'Tirit (Anadolu)', icon: '🍲', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Bayat ekmek, et suyu ve yoğurtlu.' },
  { id: 'e54', title: 'Kaymaklı Ekmek Kadayıfı', icon: '🍮', tags: ['food', 'dessert', 'high-budget', 'traditional'], description: 'Yanında bir top dondurma.' },
  { id: 'e55', title: 'Kabak Tatlısı (Cevizli)', icon: '🎃', tags: ['food', 'dessert', 'low-budget', 'home'], description: 'Tahin ve cevizle.' },
  { id: 'e56', title: 'Pide (Lahmacun Hamuru Üzerine)', icon: '🍕', tags: ['food', 'hungry', 'mid-budget', 'fast'], description: 'Evde pratik pizza.' },
  { id: 'e57', title: 'Yoğurtlu Düğü Çorbası', icon: '🥣', tags: ['food', 'light', 'low-budget', 'home'], description: 'Soğuk içilir, yaz aylarının vazgeçilmezi.' },
  { id: 'e58', title: 'Mercimek Köftesi (Yalancı)', icon: '🧆', tags: ['food', 'snack', 'low-budget', 'home', 'vegan'], description: 'Salçalı, bol yeşillikli.' },
  { id: 'e59', title: 'Haluçka (Tokat)', icon: '🥟', tags: ['food', 'hungry', 'mid-budget', 'traditional'], description: 'Erişte, kıyma ve yoğurt.' },
  { id: 'e60', title: 'Patlıcan Kebabı (Fırın)', icon: '🍆', tags: ['food', 'hungry', 'high-budget', 'traditional'], description: 'Domates soslu, köz tadında.' },


  // =================================================================
  // 💎 LÜKS & KEYİF (Maaş Günü / Date)
  // =================================================================
  { id: 'l1', title: 'Serpme Kahvaltı', icon: '🧀', tags: ['food', 'hungry', 'high-budget', 'morning', 'group'], description: 'Masada boş yer kalmasın, çay sınırsız.' },
  { id: 'l2', title: 'Ocakbaşı & Meze', icon: '🍢', tags: ['food', 'hungry', 'high-budget', 'group', 'alcohol'], description: 'Köz kokusu, atom, şakşuka.' },
  { id: 'l3', title: 'Rakı & Balık', icon: '🐟', tags: ['food', 'hungry', 'high-budget', 'group', 'alcohol', 'view'], description: 'Deniz kenarında dertleşmece.' },
  { id: 'l4', title: 'Steakhouse Burger', icon: '🍔', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Eti az pişmiş, karamelize soğanlı.' },
  { id: 'l5', title: 'Sushi Date', icon: '🍣', tags: ['food', 'hungry', 'high-budget', 'luxury', 'duo'], description: 'California Roll ile başla.' },
  { id: 'l6', title: 'İtalyan Pizza', icon: '🍷', tags: ['food', 'hungry', 'high-budget', 'romance'], description: 'İncecik hamur, mozarella, fesleğen.' },
  { id: 'l7', title: 'Künefe & Kaymak', icon: '🥞', tags: ['food', 'dessert', 'mid-budget', 'group'], description: 'Sıcak şerbet, uzayan peynir.' },
  { id: 'l8', title: 'San Sebastian', icon: '🍰', tags: ['food', 'dessert', 'mid-budget', 'cafe'], description: 'Üzerine akışkan çikolata sos.' },
  { id: 'l9', title: 'Fine Dining', icon: '🍽️', tags: ['food', 'hungry', 'high-budget', 'luxury', 'romance'], description: 'Tabakta az yemek, çok sanat.' },
  // --- YENİ EKLENEN LÜKS & KEYİF ---
  { id: 'l10', title: 'Boğazda Kahvaltı', icon: '🌉', tags: ['food', 'hungry', 'high-budget', 'view', 'romance'], description: 'Manzara eşliğinde, sınırsız çay keyfi.' },
  { id: 'l11', title: 'Meze Tabağı & Sohbet', icon: '🥗', tags: ['food', 'snack', 'mid-budget', 'group', 'talk'], description: 'Haydari, şakşuka, atom... Yeter mi?' },
  { id: 'l12', title: 'Tuzda Balık', icon: '🐟', tags: ['food', 'hungry', 'high-budget', 'luxury', 'romance'], description: 'Şovlu sunum, yanında bol salata.' },
  { id: 'l13', title: 'Geleneksel Türk Kahvesi', icon: '☕', tags: ['food', 'dessert', 'low-budget', 'cafe', 'talk'], description: 'Yanında lokum, fal kapatmak serbest.' },
  { id: 'l14', title: 'Saray Mutfağı Yemekleri', icon: '👑', tags: ['food', 'hungry', 'high-budget', 'traditional'], description: 'Osmanlı usulü, özel tatlar.' },
  { id: 'l15', title: 'Cheesecake', icon: '🍰', tags: ['food', 'dessert', 'mid-budget', 'cafe', 'duo'], description: 'Fıstıklı, balkabaklı, limonlu... Hangisi olsa?' },
  { id: 'l16', title: 'Dondurmalı İrmik Tatlısı', icon: '🍦', tags: ['food', 'dessert', 'low-budget', 'home'], description: 'Hafif ve lezzetli, tam yazlık.' },
  { id: 'l17', title: 'Masa Başı RPG Oyunu', icon: '📜', tags: ['activity', 'group', 'brain', 'fantasy'], description: 'Zar at, kaderini belirle. En az 4 kişi şart.' },
  { id: 'l18', title: 'Tiyatro/Müzikal Bileti', icon: '🎭', tags: ['activity', 'luxury', 'romance', 'culture'], description: 'Ruhunuzu besleyin, biletler pahalı.' },
  { id: 'l19', title: 'Viski & Puro Gecesi', icon: '🥃', tags: ['activity', 'luxury', 'alcohol', 'talk'], description: 'Keyifli, olgun sohbetler eşliğinde.' },
  { id: 'l20', title: 'Tasting Menü', icon: '🍷', tags: ['food', 'hungry', 'high-budget', 'luxury', 'romance'], description: 'Şefin özel tadım menüsü, yeni lezzetler dene.' },
  { id: 'l21', title: 'Şampanyalı İstiridye', icon: '🥂', tags: ['food', 'luxury', 'high-budget', 'romance'], description: 'Özel bir kutlama yemeği.' },
  { id: 'l22', title: 'Gurme Sucuklu Yumurta', icon: '🍳', tags: ['food', 'hungry', 'high-budget', 'morning'], description: 'Köy yumurtası, özel sucuk ve tereyağı.' },
  { id: 'l23', title: 'Lüks Çikolata ve Şarap', icon: '🍷', tags: ['food', 'dessert', 'high-budget', 'romance'], description: 'Kaliteli bitter çikolata ve kırmızı şarap.' },
  { id: 'l24', title: 'Şık Bir İtalyan Restoranı', icon: '🍝', tags: ['food', 'hungry', 'high-budget', 'romance'], description: 'Canlı müzik eşliğinde.' },
  { id: 'l25', title: 'Deniz Ürünleri Tabağı', icon: '🦞', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Karides, kalamar, ahtapot.' },
  { id: 'l26', title: 'Gurme Burger Festivali', icon: '🍔', tags: ['food', 'hungry', 'high-budget', 'group'], description: 'Şehrin en iyi burgerlerini dene.' },
  { id: 'l27', title: 'Özel Yöresel Kahve Tadımı', icon: '☕', tags: ['food', 'relax', 'mid-budget', 'cafe'], description: 'Farklı çekirdekleri keşfet.' },
  { id: 'l28', title: 'Geleneksel Çini Atölyesi', icon: '🎨', tags: ['activity', 'luxury', 'indoor', 'culture'], description: 'Kendi sanat eserini yarat.' },
  { id: 'l29', title: 'SPA ve Masaj Günü', icon: '🧖‍♂️', tags: ['activity', 'luxury', 'indoor', 'relax'], description: 'Tüm gün huzur ve detoks.' },
  { id: 'l30', title: 'Şarap Tadımı Turu', icon: '🍷', tags: ['activity', 'luxury', 'outdoor', 'alcohol'], description: 'Bağları ziyaret et.' },
  { id: 'l31', title: 'At Binme Dersi', icon: '🐎', tags: ['activity', 'luxury', 'outdoor', 'energetic'], description: 'Doğa ile iç içe.' },
  { id: 'l32', title: 'Helikopter Turu', icon: '🚁', tags: ['activity', 'luxury', 'energetic', 'view'], description: 'Şehri tepeden izle.' },
  { id: 'l33', title: 'Yelken Dersi', icon: '⛵', tags: ['activity', 'luxury', 'energetic', 'outdoor'], description: 'Rüzgarla dans et.' },
  { id: 'l34', title: 'Özel Şefin Masası', icon: '🍽️', tags: ['food', 'hungry', 'high-budget', 'luxury'], description: 'Şefe yakın, özel menü.' },
  { id: 'l35', title: 'Türk Sanat Müziği Konseri', icon: '🎶', tags: ['activity', 'luxury', 'indoor', 'culture'], description: 'Klasik makamları dinle.' },
  { id: 'l36', title: 'Antika Pazarı Turu', icon: '🛍️', tags: ['activity', 'lazy', 'outdoor', 'culture'], description: 'Eski eşyaların hikayesini dinle.' },
  { id: 'l37', title: 'Puro ve Konyak Gecesi', icon: '🥃', tags: ['activity', 'luxury', 'alcohol', 'talk'], description: 'Ağır, keyifli sohbetler.' },
  { id: 'l38', title: 'Lüks Otel Barında Kokteyl', icon: '🍸', tags: ['activity', 'high-budget', 'night', 'romance'], description: 'Manzaralı, sakin bir ortam.' },
  { id: 'l39', title: 'Kapalı Havuz Keyfi', icon: '🏊‍♀️', tags: ['activity', 'lazy', 'indoor', 'relax'], description: 'Soğuk havada sıcak su.' },
  { id: 'l40', title: 'Kişisel Gelişim Semineri', icon: '🧠', tags: ['activity', 'lazy', 'indoor', 'productive'], description: 'Yeni beceriler edin.' },

  // =================================================================
  // 🏠 AKTİVİTE - EVDE / TEMBEL (Chill Mode)
  // =================================================================
  { id: 'h1', title: 'Dedikodu Kazanı', icon: '🗣️', tags: ['activity', 'lazy', 'home', 'group', 'talk'], description: 'Kim kiminle ne yapmış? Stalk time.' },
  { id: 'h2', title: 'Korku Gecesi', icon: '👻', tags: ['activity', 'lazy', 'home', 'group', 'thrill'], description: 'Işıkları kapat, Dabbe serisine başla.' },
  { id: 'h3', title: 'Balkon Keyfi', icon: '☕', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Çayını al, geleni geçeni izle, hayatı sorgula.' },
  { id: 'h4', title: 'Telefonda Okey/Batak', icon: '📱', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Seri seri oyna, çip kazan.' },
  { id: 'h5', title: 'Eski Türk Filmi', icon: '🎥', tags: ['activity', 'lazy', 'home', 'family'], description: 'Tosun Paşa veya Süt Kardeşler izle.' },
  { id: 'h6', title: 'Dip Köşe Temizlik', icon: '🧹', tags: ['activity', 'energetic', 'home', 'productive'], description: 'Müziği aç, evi pırıl pırıl yap.' },
  { id: 'h7', title: 'Gardırop Detoksu', icon: '👕', tags: ['activity', 'energetic', 'home', 'productive'], description: 'Giymediklerini ayır, ferahla.' },
  { id: 'h8', title: 'Sanal Menü Turu', icon: '🛵', tags: ['activity', 'lazy', 'home', 'hungry'], description: 'Sipariş verme, sadece yemeklere bakıp hayal kur.' },
  { id: 'h9', title: 'Kedi/Köpek Videoları', icon: '🐈', tags: ['activity', 'lazy', 'home', 'relax'], description: 'YouTube\'a gir, saatlerce çıkama.' },
  { id: 'h10', title: 'Altın Günü Modu', icon: '🥗', tags: ['activity', 'lazy', 'home', 'group', 'food'], description: 'Kısır yap, çay demle, gıybet yap.' },
  { id: 'h11', title: 'Türk Kahvesi & Fal', icon: '🔮', tags: ['activity', 'lazy', 'home', 'duo'], description: 'Faladdin\'e at veya kendin salla.' },
  { id: 'h12', title: 'FIFA / PES Turnuvası', icon: '🎮', tags: ['activity', 'lazy', 'home', 'group'], description: 'Kolu bozuk olan kaybetsin.' },
  { id: 'h13', title: '90lar Türkçe Pop', icon: '🎸', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Tarkan, Mustafa Sandal, dans!' },
  { id: 'h14', title: 'Kutu Oyunu (Monopoly)', icon: '🎲', tags: ['activity', 'lazy', 'home', 'group'], description: 'Arkadaşlarını iflas ettir, kavga çıkar.' },
  { id: 'h15', title: 'Sessiz Sinema', icon: '🤫', tags: ['activity', 'energetic', 'home', 'group'], description: 'En zor filmi anlatmaya çalış.' },
  { id: 'h16', title: 'Cilt Bakımı', icon: 'mask', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Maskeni yap, salatalıkları gözüne koy.' },
  { id: 'h17', title: 'Yoga / Meditasyon', icon: '🧘', tags: ['activity', 'lazy', 'home', 'relax'], description: '10 dakika nefes egzersizi yap.' },
  // --- YENİ EKLENEN EV AKTİVİTELERİ ---
  { id: 'h18', title: 'Yeni Bir Diziye Başla', icon: '📺', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Maksimum 2 sezonluk olsun, bağımlı olma.' },
  { id: 'h19', title: 'Eski Fotoğraflara Bak', icon: '📸', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Nerede o eski bayramlar...' },
  { id: 'h20', title: 'Görüntülü Konuşma (Gıybet)', icon: '📱', tags: ['activity', 'lazy', 'home', 'group', 'talk'], description: 'Aç telefonu, herkesi topla.' },
  { id: 'h21', title: 'Kıyafet Kombinle', icon: '👚', tags: ['activity', 'lazy', 'home', 'productive'], description: 'Yarın ne giyeceğini şimdiden hazırla.' },
  { id: 'h22', title: 'Dil Öğrenmeye Başla', icon: '🗣️', tags: ['activity', 'lazy', 'home', 'productive'], description: 'Duolingo\'da birkaç ders yap.' },
  { id: 'h23', title: 'Kitap Oku', icon: '📚', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Oturma pozisyonunu ayarla, telefon sessizde.' },
  { id: 'h24', title: 'Sosyal Medyadan Uzak Dur', icon: '📵', tags: ['activity', 'relax', 'home', 'solo'], description: 'Bir saatliğine telefonu bırak, detoks yap.' },
  { id: 'h25', title: 'Sıcak Çikolata Keyfi', icon: '🍫', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Battaniye altı, film üstü.' },
  { id: 'h26', title: 'Evde Spor Yap', icon: '🏋️', tags: ['activity', 'energetic', 'home', 'solo'], description: 'YouTube\'dan 20 dakikalık bir kardiyo videosu aç.' },
  { id: 'h27', title: 'Makarna Yapma Challenge', icon: '🍝', tags: ['activity', 'lazy', 'home', 'food', 'duo'], description: 'En iyi sosu kim yapacak yarışması.' },
  { id: 'h28', title: 'Podcast Dinle', icon: '🎙️', tags: ['activity', 'lazy', 'home', 'solo', 'relax'], description: 'Sessiz bir köşede bilgi veya mizah dinle.' },
  { id: 'h29', title: 'Müzik Enstrümanı Çal', icon: '🥁', tags: ['activity', 'energetic', 'home', 'solo'], description: 'Komşuları rahatsız etme, kulaklıkla çalış.' },
  { id: 'h30', title: 'Yeni Bir Yemek Pişir', icon: '👨‍🍳', tags: ['activity', 'lazy', 'home', 'food'], description: 'YouTube\'dan zor bir tarif dene.' },
  { id: 'h31', title: 'Evde Boyama Yap', icon: '🎨', tags: ['activity', 'lazy', 'home', 'art'], description: 'Suluboya veya kuru boya ile rahatla.' },
  { id: 'h32', title: 'Kitaplık Düzenleme', icon: '📚', tags: ['activity', 'lazy', 'home', 'productive'], description: 'Okunmayanları ayır, tozunu al.' },
  { id: 'h33', title: 'Evde Karaoke', icon: '🎤', tags: ['activity', 'energetic', 'home', 'group', 'fun'], description: 'YouTube\'dan altyazılı şarkı aç.' },
  { id: 'h34', title: 'En Sevdiğin Filmi Yeniden İzle', icon: '🎥', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Klasiklere geri dön.' },
  { id: 'h35', title: 'Eski Konsol Oyunu Oyna', icon: '🎮', tags: ['activity', 'lazy', 'home', 'solo', 'group'], description: 'PS1 veya Atari\'ye geri dön.' },
  { id: 'h36', title: 'Evde Kokteyl Denemeleri', icon: '🍸', tags: ['activity', 'lazy', 'home', 'alcohol'], description: 'Yeni tatlar keşfet.' },
  { id: 'h37', title: 'Uzun Bir Banyo/Duş', icon: '🛁', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Mumlar, müzik ve bol köpük.' },
  { id: 'h38', title: 'Evcil Hayvanla Oyna', icon: '🐕', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Onu yor, sen de rahatla.' },
  { id: 'h39', title: 'Mektup Yaz (Eskiden Kalan)', icon: '💌', tags: ['activity', 'lazy', 'home', 'talk'], description: 'Dijital dünyadan uzak bir nostalji.' },
  { id: 'h40', title: 'Evdeki Bitkileri Sula/Bakım Yap', icon: '🌱', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Doğayla bağlantı kur.' },
  { id: 'h41', title: 'Online Kursa Başla', icon: '💻', tags: ['activity', 'lazy', 'home', 'productive'], description: 'Yeni bir dil veya yazılım öğren.' },
  { id: 'h42', title: 'Tarot/Kahve Falı Bak', icon: '🔮', tags: ['activity', 'lazy', 'home', 'duo'], description: 'Geleceği tahmin etmeye çalış.' },
  { id: 'h43', title: 'Evde Pazar Keyfi', icon: '📰', tags: ['activity', 'lazy', 'home', 'morning', 'relax'], description: 'Gazete/dergi okuyarak.' },
  { id: 'h44', title: 'Kışlık/Yazlıkları Ayır', icon: '👕', tags: ['activity', 'energetic', 'home', 'productive'], description: 'Mevsimlik değişim zamanı.' },
  { id: 'h45', title: 'Podcast veya Sesli Kitap Dinle', icon: '🎧', tags: ['activity', 'lazy', 'home', 'solo', 'relax'], description: 'Gözlerini yorma, sadece dinle.' },
  { id: 'h46', title: 'Kendi Filmini Çek (Kısa Video)', icon: '📹', tags: ['activity', 'energetic', 'home', 'fun'], description: 'Komik bir hikaye uydur.' },
  { id: 'h47', title: 'Lego/Yapı Seti Kur', icon: '🧱', tags: ['activity', 'lazy', 'home', 'brain'], description: 'Odaklanma becerini geliştir.' },
  { id: 'h48', title: 'Evde Dijital Detoks', icon: '📵', tags: ['activity', 'relax', 'home', 'solo'], description: '1 saat tüm ekranları kapat.' },
  { id: 'h49', title: 'Soğuk Kahve Yapma Yarışması', icon: '☕', tags: ['food', 'lazy', 'home', 'duo'], description: 'En iyi Buzlu Latte kimde?' },
  { id: 'h50', title: 'Dizi İzle (Farklı Bir Dilde)', icon: '🌍', tags: ['activity', 'lazy', 'home', 'solo'], description: 'Dil pratiği yap.' },
  { id: 'h51', title: 'Kendi Kombinlerini Çiz', icon: '👗', tags: ['activity', 'lazy', 'home', 'art'], description: 'Moda tasarımcısı ol.' },
  { id: 'h52', title: 'Eski Telefonları Karıştır', icon: '📱', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Nostaljik fotoğraflar bul.' },
  { id: 'h53', title: 'Sosyal Medya Temizliği', icon: '🧹', tags: ['activity', 'lazy', 'home', 'productive'], description: 'Takip etmediklerini sil.' },
  { id: 'h54', title: 'Aile Reçetesi Dene', icon: '👵', tags: ['activity', 'lazy', 'home', 'food', 'traditional'], description: 'Anneannenin mantısını yap.' },
  { id: 'h55', title: 'Evde Yoga/Pilates Videosu Aç', icon: '🧘', tags: ['activity', 'lazy', 'home', 'relax', 'energetic'], description: 'Vücudunu esnet.' },
  { id: 'h56', title: 'Evde Sessiz Film Yap', icon: '🤫', tags: ['activity', 'energetic', 'home', 'group', 'fun'], description: 'Oynayın ve tahmin edin.' },
  { id: 'h57', title: 'Kendi Bitki Çayını Yap', icon: '☕', tags: ['food', 'lazy', 'home', 'healthy'], description: 'Taze nane, limon, bal.' },
  { id: 'h58', title: 'Online Satranç Oyna', icon: '♟️', tags: ['activity', 'lazy', 'home', 'solo', 'brain'], description: 'Beyin jimnastiği.' },
  { id: 'h59', title: 'Kış Uykusuna Yat', icon: '😴', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Kaliteli bir kestirme.' },
  { id: 'h60', title: 'Evde Kendi Spa Geceni Yap', icon: '🛁', tags: ['activity', 'lazy', 'home', 'relax'], description: 'Yüz maskesi, ayak banyosu.' },

  // =================================================================
  // 🌳 AKTİVİTE - DIŞARI / SOSYAL (Gezme Tozma)
  // =================================================================
  { id: 'o1', title: 'Halı Saha Maçı', icon: '⚽', tags: ['activity', 'energetic', 'outdoor', 'group'], description: 'Maç sonu baklavayı kaybeden öder.' },
  { id: 'o2', title: 'Sahilde Yürüyüş', icon: '🌊', tags: ['activity', 'energetic', 'outdoor', 'relax', 'free'], description: 'Çekirdek çitleyerek piyasa yap.' },
  { id: 'o3', title: 'AVM Turu', icon: '🛍️', tags: ['activity', 'lazy', 'indoor', 'walk'], description: 'Klima serinliğinde vitrin bak, hiçbir şey alma.' },
  { id: 'o4', title: 'Nargile Kafe', icon: '💨', tags: ['activity', 'lazy', 'outdoor', 'group', 'smoke'], description: 'Elmalı nane, köz getir abim.' },
  { id: 'o5', title: 'Okey Salonu', icon: '🎲', tags: ['activity', 'lazy', 'indoor', 'group'], description: 'Taş çalma, çaylar şirketten.' },
  { id: 'o6', title: 'Bowling Kapışması', icon: '🎳', tags: ['activity', 'energetic', 'indoor', 'group'], description: 'Topu yan kanala atma rekoru kır.' },
  { id: 'o7', title: 'Sinema Keyfi', icon: '🍿', tags: ['activity', 'lazy', 'indoor', 'group'], description: 'Mısırın en büyüğünü al.' },
  { id: 'o8', title: 'Lunapark Adrenalini', icon: '🎡', tags: ['activity', 'energetic', 'outdoor', 'fun'], description: 'Gondola binip çığlık at, kamikaze yap.' },
  { id: 'o9', title: 'Hamam / Spa', icon: '🧖‍♂️', tags: ['activity', 'lazy', 'indoor', 'relax'], description: 'Kese attır, pamuk gibi ol.' },
  { id: 'o10', title: 'Mangal Partisi', icon: '🍖', tags: ['activity', 'energetic', 'outdoor', 'group', 'food'], description: 'Yellerim yellerim bitmez.' },
  { id: 'o11', title: 'Semt Pazarı', icon: '🍅', tags: ['activity', 'energetic', 'outdoor', 'crowd'], description: 'Akşam pazarı ucuzluğu kovala, taze meyve al.' },
  { id: 'o12', title: 'Balık Tutmak', icon: '🎣', tags: ['activity', 'lazy', 'outdoor', 'relax'], description: 'Galata köprüsünde sabır testi.' },
  { id: 'o13', title: 'Go-Kart', icon: '🏎️', tags: ['activity', 'energetic', 'outdoor', 'fun'], description: 'İçindeki trafik canavarını piste sal.' },
  { id: 'o14', title: 'Müze Gezisi', icon: '🏛️', tags: ['activity', 'energetic', 'indoor', 'culture'], description: 'Müze kartın varsa bedava, kültürlen.' },
  { id: 'o15', title: 'Vapur Sefası', icon: '🚢', tags: ['activity', 'lazy', 'outdoor', 'view'], description: 'Dışarıda otur, martılara simit at.' },
  { id: 'o16', title: 'İnternet Kafe', icon: '💻', tags: ['activity', 'energetic', 'indoor', 'group'], description: 'CS:GO veya LoL kapışması.' },
  { id: 'o17', title: 'Kütüphane', icon: '📚', tags: ['activity', 'lazy', 'indoor', 'quiet'], description: 'Ders çalışır gibi yap, etrafı kes.' },
  { id: 'o18', title: 'Bilardo', icon: '🎱', tags: ['activity', 'energetic', 'indoor', 'group'], description: 'Amerikan mı, 3 bant mı? Şansını dene.' },
  { id: 'o19', title: 'Fasıl Gecesi', icon: '🎻', tags: ['activity', 'energetic', 'indoor', 'high-budget', 'alcohol'], description: 'Dertli şarkılarda ağla, göbek at.' },
  { id: 'o20', title: 'Fotoğraf Turu', icon: '📸', tags: ['activity', 'energetic', 'outdoor', 'art'], description: 'Instagram için malzeme çıkar, gün batımını yakala.' },
  { id: 'o21', title: 'Korku Evi', icon: '🧟', tags: ['activity', 'energetic', 'indoor', 'group', 'thrill'], description: 'Çığlık atma garantili, şifreleri çöz.' },
  { id: 'o22', title: 'Escape Room', icon: '🔐', tags: ['activity', 'energetic', 'indoor', 'group', 'brain'], description: 'Odadan kaçış, zekanı kullan.' },
  { id: 'o23', title: 'Konser', icon: '🎵', tags: ['activity', 'energetic', 'outdoor', 'crowd'], description: 'Sevdiğin grup gelmiş, kaçırma.' },
  { id: 'o24', title: 'Kamp Yap', icon: '⛺', tags: ['activity', 'energetic', 'outdoor', 'nature'], description: 'Şehirden kaç, ateş yak, yıldızları izle.' },
  // --- YENİ EKLENEN DIŞARI AKTİVİTELERİ ---
  { id: 'o25', title: 'Deniz Kenarında Çay', icon: '🌊', tags: ['activity', 'lazy', 'outdoor', 'view', 'relax'], description: 'Martılara simit at, huzur bul.' },
  { id: 'o26', title: 'Tarihi Yarımada Gezisi', icon: '🕌', tags: ['activity', 'energetic', 'outdoor', 'culture'], description: 'Sultanahmet, Ayasofya, Yerebatan Sarnıcı...' },
  { id: 'o27', title: 'Canlı Müzik Performansı', icon: '🎵', tags: ['activity', 'lazy', 'outdoor', 'night', 'group'], description: 'Gözlerinizi kapatın, müziği hissedin.' },
  { id: 'o28', title: 'Piknik Yap', icon: '🧺', tags: ['activity', 'energetic', 'outdoor', 'group', 'food'], description: 'Doğayla iç içe, mangalsız piknik.' },
  { id: 'o29', title: 'Bisiklet Turu', icon: '🚲', tags: ['activity', 'energetic', 'outdoor', 'solo'], description: 'Rüzgarı hisset, pedala bas.' },
  { id: 'o30', title: 'Masa Tenisi / Langırt', icon: '🏓', tags: ['activity', 'energetic', 'indoor', 'group'], description: 'Turnuva başlasın, iddia önemli.' },
  { id: 'o31', title: 'Büyük Bir Parkta Yürüyüş', icon: '🌳', tags: ['activity', 'lazy', 'outdoor', 'relax'], description: 'Güneşli havada uzun bir tur.' },
  { id: 'o32', title: 'Eski Bir Semti Keşfet', icon: '🏘️', tags: ['activity', 'energetic', 'outdoor', 'culture'], description: 'Fotoğraf çekmeyi unutma.' },
  { id: 'o33', title: 'Streetball / Basket', icon: '🏀', tags: ['activity', 'energetic', 'outdoor', 'group'], description: 'Smaç basmaya çalışmayın, bileğinize dikkat edin.' },
  { id: 'o34', title: 'Kitap Kafede Çalışma', icon: '📖', tags: ['activity', 'lazy', 'indoor', 'quiet', 'solo'], description: 'Hem ders çalış, hem sosyalleş.' },
  { id: 'o35', title: 'Kapalı Çarşı / Mısır Çarşısı', icon: '🛍️', tags: ['activity', 'lazy', 'indoor', 'culture'], description: 'Tarihi dokuyu hisset, belki bir şeyler alırsın.' },
  { id: 'o36', title: 'Plaj Voleybolu', icon: '🏐', tags: ['activity', 'energetic', 'outdoor', 'group', 'fun'], description: 'Güneş, kum, ter... İşte yaz!' },
  { id: 'o37', title: 'Kayak/Snowboard', icon: '⛷️', tags: ['activity', 'energetic', 'outdoor', 'high-budget', 'thrill'], description: 'Kış sporlarının adrenalini.' },
  { id: 'o38', title: 'Seramik Atölyesi', icon: '🎨', tags: ['activity', 'lazy', 'indoor', 'art', 'duo'], description: 'Yaratıcılığını konuştur, çamurla oyna.' },
  { id: 'o39', title: 'Trekking / Doğa Yürüyüşü', icon: '⛰️', tags: ['activity', 'energetic', 'outdoor', 'nature'], description: 'Temiz hava, bol oksijen. Dağlara doğru.' },
  { id: 'o40', title: 'Balon Turu İzle', icon: '🎈', tags: ['activity', 'lazy', 'outdoor', 'view', 'morning'], description: 'Gün doğumu eşliğinde, Kapadokya hayali kur.' },
  { id: 'o41', title: 'Teleferikle Zirveye Çık', icon: '🚠', tags: ['activity', 'lazy', 'outdoor', 'view'], description: 'Şehrin veya dağın manzarasını izle.' },
  { id: 'o42', title: 'İstanbul/İzmir Turları', icon: '🌉', tags: ['activity', 'lazy', 'outdoor', 'view'], description: 'Turist gibi gez, fotoğraf çek.' },
  { id: 'o43', title: 'Eskimo Kavgası (Kar Topu)', icon: '☃️', tags: ['activity', 'energetic', 'outdoor', 'fun'], description: 'Kar yağdıysa dışarı!' },
  { id: 'o44', title: 'Bisikletle Adaları Turlamak', icon: '🚲', tags: ['activity', 'energetic', 'outdoor', 'nature'], description: 'Şehirden kaçış.' },
  { id: 'o45', title: 'Street Food Festivali', icon: '🍔', tags: ['activity', 'energetic', 'outdoor', 'food'], description: 'Farklı lezzetleri dene.' },
  { id: 'o46', title: 'Açık Hava Sineması', icon: '🍿', tags: ['activity', 'lazy', 'outdoor', 'romance'], description: 'Yaz akşamı klasiği.' },
  { id: 'o47', title: 'Sokak Müzisyenlerini Dinle', icon: '🎸', tags: ['activity', 'lazy', 'outdoor', 'relax', 'free'], description: 'Kahveni al, bir köşede otur.' },
  { id: 'o48', title: 'Dağ Evi Kirala (Şömine Başında)', icon: '🏡', tags: ['activity', 'luxury', 'outdoor', 'relax'], description: 'Soğukta sıcak keyif.' },
  { id: 'o49', title: 'Paintball Maçı', icon: '🔫', tags: ['activity', 'energetic', 'outdoor', 'group', 'thrill'], description: 'Bolca boya ve adrenalin.' },
  { id: 'o50', title: 'Kapalıçarşı Alışverişi', icon: '🛍️', tags: ['activity', 'lazy', 'indoor', 'culture'], description: 'Hediyelik eşya bak.' },
  { id: 'o51', title: 'Trambolin Parkı', icon: '🤸‍♀️', tags: ['activity', 'energetic', 'indoor', 'fun'], description: 'Çocuk gibi zıpla.' },
  { id: 'o52', title: 'Tarihi Hamam Deneyimi', icon: '🧖‍♂️', tags: ['activity', 'lazy', 'indoor', 'relax', 'culture'], description: 'Geleneksel kese ve köpük.' },
  { id: 'o53', title: 'Tema Park (Vialand vb.)', icon: '🎡', tags: ['activity', 'energetic', 'outdoor', 'thrill'], description: 'Hız trenleri ve eğlence.' },
  { id: 'o54', title: 'Çiftlik Ziyareti', icon: '🐄', tags: ['activity', 'lazy', 'outdoor', 'nature'], description: 'Hayvanlarla vakit geçir.' },
  { id: 'o55', title: 'Kapalı Buz Pateni Pisti', icon: '⛸️', tags: ['activity', 'energetic', 'indoor', 'fun'], description: 'Düşe kalka öğren.' },
  { id: 'o56', title: 'Okçuluk Dersi', icon: '🏹', tags: ['activity', 'lazy', 'outdoor', 'energetic'], description: 'Nişan alma yeteneğini geliştir.' },
  { id: 'o57', title: 'Karting (Kapalı Alan)', icon: '🏎️', tags: ['activity', 'energetic', 'indoor', 'fun'], description: 'Islak zeminde drift.' },
  { id: 'o58', title: 'Rock Konseri', icon: '🤘', tags: ['activity', 'energetic', 'outdoor', 'crowd', 'night'], description: 'En sevdiğin grubun önünde.' },
  { id: 'o59', title: 'Salsa/Bachata Gecesi', icon: '💃', tags: ['activity', 'energetic', 'indoor', 'romance'], description: 'Dans etmeye git.' },
  { id: 'o60', title: 'Bit Pazarı Turu', icon: '🖼️', tags: ['activity', 'lazy', 'outdoor', 'culture'], description: 'Eski hazineleri ara.' },
  { id: 'o61', title: 'Tiyatroya Git (Komedi)', icon: '🎭', tags: ['activity', 'lazy', 'indoor', 'culture'], description: 'Bol kahkahalı bir gece.' },
  { id: 'o62', title: 'Çay Bahçesinde Okey', icon: '🎲', tags: ['activity', 'lazy', 'outdoor', 'group', 'talk'], description: 'Geleneksel okey keyfi.' },
  { id: 'o63', title: 'Kendi Şehrinde Turist Ol', icon: '🧭', tags: ['activity', 'energetic', 'outdoor', 'culture'], description: 'Hiç gitmediğin bir mahalleyi keşfet.' },
  { id: 'o64', title: 'Akşam Yemeği (Farklı Mutfak)', icon: '🌮', tags: ['food', 'hungry', 'mid-budget', 'indoor', 'romance'], description: 'Tayland, Meksika, Lübnan mutfağı dene.' },
  { id: 'o65', title: 'Hayvan Barınağı Ziyareti', icon: '🐶', tags: ['activity', 'lazy', 'outdoor', 'relax'], description: 'Gönüllü ol, onlara zaman ayır.' },
  { id: 'o66', title: 'Kız Kulesi\'ne Git (Üsküdar)', icon: '🗼', tags: ['activity', 'lazy', 'outdoor', 'view', 'romance'], description: 'İstanbul Boğazı\'nın incisi.' },
  { id: 'o67', title: 'Köy Pazarı Gezisi', icon: '🍅', tags: ['activity', 'lazy', 'outdoor', 'food'], description: 'Doğal ve taze ürünler al.' },
  { id: 'o68', title: 'Su Kayağı (Yazın)', icon: '🏄‍♂️', tags: ['activity', 'energetic', 'outdoor', 'thrill'], description: 'Denizde adrenalin.' },
  { id: 'o69', title: 'Kitapçıda Saatler Geçir', icon: '📚', tags: ['activity', 'lazy', 'indoor', 'solo'], description: 'Yeni kitaplar keşfet.' },
  { id: 'o70', title: 'Tarihi Sinemada Matine', icon: '🎥', tags: ['activity', 'lazy', 'indoor', 'culture'], description: 'Eski sinema atmosferi.' },
  { id: 'o71', title: 'Dağ Bisikleti Turu', icon: '⛰️', tags: ['activity', 'energetic', 'outdoor', 'thrill'], description: 'Yokuş yukarı tırman.' },
  { id: 'o72', title: 'Plajda Güneşlen ve Yüz', icon: '☀️', tags: ['activity', 'lazy', 'outdoor', 'relax'], description: 'Kum, deniz ve huzur.' },
  { id: 'o73', title: 'Şehirden Uzak Ormanda Yürüyüş', icon: '🌳', tags: ['activity', 'energetic', 'outdoor', 'nature'], description: 'Doğanın sesini dinle.' },
  { id: 'o74', title: 'Bungee Jumping (Cesaret!)', icon: '🧗', tags: ['activity', 'energetic', 'outdoor', 'thrill'], description: 'Hayatında bir kere.' },
  { id: 'o75', title: 'Bowling ve Atıştırmalık', icon: '🎳', tags: ['activity', 'lazy', 'indoor', 'group', 'food'], description: 'Eğlencenin yanında cips ve kola.' },
  { id: 'o76', title: 'Şehirdeki En Eski Pastane', icon: '🍰', tags: ['food', 'snack', 'mid-budget', 'cafe'], description: 'Tarihi lezzetleri dene.' },
  { id: 'o77', title: 'Canlı Jazz/Blues Performansı', icon: '🎷', tags: ['activity', 'lazy', 'indoor', 'night'], description: 'Kaliteli müzik.' },
  { id: 'o78', title: 'İstanbul Boğazı Tekne Turu', icon: '🚢', tags: ['activity', 'luxury', 'outdoor', 'view'], description: 'Lüks bir akşam yemeği eşliğinde.' },
  { id: 'o79', title: 'Halka Açık Tenis Kortu', icon: '🎾', tags: ['activity', 'energetic', 'outdoor', 'duo'], description: 'Raketini kap gel.' },
  { id: 'o80', title: 'Akşam Vapuru ve Çay', icon: '🚢', tags: ['activity', 'lazy', 'outdoor', 'relax', 'view'], description: 'Gün batımını denizden izle.' }
];

// SİHİRBAZ SORULARI (Değişmeden kalabilir, veri ile uyumlu)
export type QuestionType = {
  id: string;
  text: string;
  options: { label: string; value: string; nextStep: string | 'FINISH' }[];
};

export const WIZARD_STEPS: Record<string, QuestionType> = {
  'START': {
    id: 'step1',
    text: 'Selam Kardeşim! 👋\nBugün ortam nasıl?',
    options: [
      { label: 'Tek Tabancayım 🤠', value: 'solo', nextStep: 'MOOD_SOLO' },
      { label: 'Kankamla/Manitayla 👯', value: 'duo', nextStep: 'MOOD_GROUP' },
      { label: 'Aşiret Gibiyiz (Kalabalık) 🎉', value: 'group', nextStep: 'MOOD_GROUP' },
    ]
  },
  'MOOD_SOLO': {
    id: 'step2_solo',
    text: 'Peki, modun nasıl?',
    options: [
      { label: 'Kurt Gibi Açım 🐺', value: 'hungry', nextStep: 'BUDGET' },
      { label: 'Sıkıldım, Aktivite Lazım 🥱', value: 'bored', nextStep: 'ENERGY' },
      { label: 'Kafamı Dinleyeceğim 🧘', value: 'relax', nextStep: 'LOCATION_HOME' },
    ]
  },
  'MOOD_GROUP': {
    id: 'step2_group',
    text: 'Ekibin havası nasıl?',
    options: [
      { label: 'Herkes Açlıktan Ölüyor 🍕', value: 'hungry', nextStep: 'BUDGET' },
      { label: 'Eğlenmek İstiyoruz 🥳', value: 'fun', nextStep: 'ENERGY' },
      { label: 'Laklak Yapalım 🗣️', value: 'talk', nextStep: 'LOCATION_OUT' },
    ]
  },
  'BUDGET': {
    id: 'step3_budget',
    text: 'Cüzdanlar ne durumda?',
    options: [
      { label: 'Ay sonu (Öğrenci İşi) 💸', value: 'low-budget', nextStep: 'FINISH' },
      { label: 'Esnaf İşi (Orta) 💳', value: 'mid-budget', nextStep: 'FINISH' },
      { label: 'Maaş Yattı (Krallar Gibi) 👑', value: 'high-budget', nextStep: 'FINISH' },
    ]
  },
  'ENERGY': {
    id: 'step3_energy',
    text: 'Enerjiniz ne seviyede?',
    options: [
      { label: 'Pil bitik, yorma bizi 🪫', value: 'lazy', nextStep: 'LOCATION_HOME' },
      { label: 'Enerji tavan, uçarız! 🔋', value: 'energetic', nextStep: 'LOCATION_OUT' },
    ]
  },
  'LOCATION_HOME': {
    id: 'step4_home',
    text: 'Nerede takılmak istersin?',
    options: [
      { label: 'Evden çıkmam 🏠', value: 'home', nextStep: 'FINISH' },
      { label: 'Belki balkona çıkarız 🌇', value: 'home', nextStep: 'FINISH' },
    ]
  },
  'LOCATION_OUT': {
    id: 'step4_out',
    text: 'Mekan tercihin?',
    options: [
      { label: 'Açık hava olsun ☀️', value: 'outdoor', nextStep: 'FINISH' },
      { label: 'Kapalı mekan olsun 🏢', value: 'indoor', nextStep: 'FINISH' },
    ]
  }
};